In [1]:
import pandas as pd
import numpy as np
from kemeny.scf.borda import *
from kemeny.scf.condorcet import *
from kemeny.scf.distance import dRP
#import kemeny.scf.initialization as init
#import kemeny.azzinimunda.azzinimunda0 as am0
#import kemeny.azzinimundºa.azzinimunda0b as am0b
#import kemeny.azzinimunda.azzinimunda1 as am1
#import kemeny.azzinimunda.azzinimunda1rec as am1rec
#import kemeny.azzinimunda.azzinimunda2 as am2
import kemeny.azzinimunda.azzinimunda3 as am3
import kemeny.azzinimunda.azzinimunda4 as am4
import time
import sys

SCF loaded


In [2]:
om = np.array([
[0,2,5,7,3,5,4,7,5,4,5,4],
[8,0,6,6,5,9,4,9,7,4,4,6],
[5,4,0,4,3,6,3,6,5,4,4,2],
[3,4,6,0,3,6,3,8,5,4,4,2],
[7,5,7,7,0,10,5,9,9,5,5,4],
[5,1,4,4,0,0,3,7,4,4,4,2],
[6,6,7,7,5,7,0,9,7,7,6,6],
[3,1,4,2,1,3,1,0,2,3,4,2],
[5,3,5,5,1,6,3,8,0,3,4,3],
[6,6,6,6,5,6,3,7,7,0,6,4],
[5,6,6,6,5,6,4,6,6,4,0,4],
[6,4,8,8,6,8,4,8,7,6,6,0]])

rep = 3

times = np.zeros(rep)
for i in range(rep):
    # Algorithm with Condorcet winner
    algorithm = am3.AzziniMunda3(om) 
    start_time = time.time()
    sol = algorithm.execute()
    t = (time.time() - start_time)
    times[i] = t
    #print(t)
exec_time = np.median(times)
print(sol)
print(exec_time)

times = np.zeros(rep)
for i in range(rep):
    # Algorithm with Condorcet winner
    algorithm = am4.AzziniMunda4(om) 
    start_time = time.time()
    sol = algorithm.execute()
    t = (time.time() - start_time)
    times[i] = t
    #print(t)
exec_time = np.median(times)
print(sol)
print(exec_time)

[[ 6  5  8  7  2 10  0 11  9  3  4  1]
 [ 6  5  9  7  2 10  0 11  8  3  4  1]
 [ 6  5  9  8  2 10  0 11  7  3  4  1]
 [ 7  5  9  8  2 10  0 11  6  3  4  1]
 [ 6  5  8  7  3 10  0 11  9  2  4  1]
 [ 6  5  9  7  3 10  0 11  8  2  4  1]
 [ 6  5  9  8  3 10  0 11  7  2  4  1]
 [ 7  5  9  8  3 10  0 11  6  2  4  1]
 [ 6  4  8  7  5 10  0 11  9  2  3  1]
 [ 6  4  9  7  5 10  0 11  8  2  3  1]
 [ 6  4  9  8  5 10  0 11  7  2  3  1]
 [ 7  4  9  8  5 10  0 11  6  2  3  1]
 [ 6  5  8  7  4 10  0 11  9  2  3  1]
 [ 6  5  9  7  4 10  0 11  8  2  3  1]
 [ 6  5  9  8  4 10  0 11  7  2  3  1]
 [ 7  5  9  8  4 10  0 11  6  2  3  1]]
7.291900157928467
[ 2  7  2  3  6  1 10  0  2  8  6  9]
[ 2  7  2  3  6  1 10  0  2  8  6  9]
[ 2  7  2  3  6  1 10  0  2  8  6  9]
[[ 6  5  8  7  2 10  0 11  9  3  4  1]
 [ 6  5  9  7  2 10  0 11  8  3  4  1]
 [ 6  5  9  8  2 10  0 11  7  3  4  1]
 [ 7  5  9  8  2 10  0 11  6  3  4  1]
 [ 6  5  8  7  3 10  0 11  9  2  4  1]
 [ 6  5  9  7  3 10  0 11  8  2  4  1]
 [ 6  5  

In [3]:
a = np.array([False, True, True, False, True])
a.sum()

3

In [24]:
om = np.array([
[0,2,5,7,3,5,4,7,5,4,5,4],
[8,0,6,6,5,9,4,9,7,4,4,6],
[5,4,0,4,3,6,3,6,5,4,4,2],
[3,4,6,0,3,6,3,8,5,4,4,2],
[7,5,7,7,0,10,5,9,9,5,5,4],
[5,1,4,4,0,0,3,7,4,4,4,2],
[6,6,7,7,5,7,0,9,7,7,6,6],
[3,1,4,2,1,3,1,0,2,3,4,2],
[5,3,5,5,1,6,3,8,0,3,4,3],
[6,6,6,6,5,6,3,7,7,0,6,4],
[5,6,6,6,5,6,4,6,6,4,0,4],
[6,4,8,8,6,8,4,8,7,6,6,0]])

rep = 3

times = np.zeros(rep)
for i in range(rep):
    # Algorithm with Condorcet winner
    algorithm = am0.AzziniMunda0(om) 
    start_time = time.time()
    sol = algorithm.execute()
    t = (time.time() - start_time)
    times[i] = t
    #print(t)
exec_time = np.median(times)
print(exec_time)

times = np.zeros(rep)
for i in range(rep):
    # Algorithm with Condorcet winner
    algorithm = am0b.AzziniMunda0(om) 
    start_time = time.time()
    sol = algorithm.execute()
    t = (time.time() - start_time)
    times[i] = t
    #print(t)
exec_time = np.median(times)

299.9248242378235
307.79731011390686
print(exec_time)

73.10952806472778
75.02573490142822


In [17]:
n = 4
m = 10
(np.arange(n)*m//2)[::-1]

array([15, 10,  5,  0])

In [18]:
om = np.array([
[0,6,9,4,6,5,6,7,7,7,5,6,6,4,8],
[4,0,4,4,6,4,3,3,4,6,3,4,5,4,6],
[1,6,0,4,4,4,4,3,4,5,4,4,3,2,6],
[6,6,6,0,6,4,4,6,6,4,6,4,5,6,7],
[4,4,6,4,0,3,3,4,4,5,3,4,7,4,7],
[5,6,6,6,7,0,6,4,7,5,4,7,6,6,7],
[4,7,6,6,7,4,0,6,6,6,6,7,7,6,7],
[3,7,7,4,6,6,4,0,6,6,3,5,7,4,8],
[3,6,6,4,6,3,4,4,0,6,3,4,6,4,6],
[3,4,5,6,5,5,4,4,4,0,4,3,6,5,7],
[5,7,6,4,7,6,4,7,7,6,0,5,8,6,8],
[4,6,6,6,6,3,3,5,6,7,5,0,6,4,6],
[4,5,7,5,3,4,3,3,4,4,2,4,0,3,7],
[6,6,8,4,6,4,4,6,6,5,4,6,7,0,7],
[2,4,4,3,3,3,3,2,4,3,2,4,3,3,0]])


# Inicializando con inf 325.75592827796936
r = ranking_to_lineal(borda(om))
print(r)
d = dRP(r, om)
print(d)

print(dRP(np.array([5,9, 13,  2, 10,  0,  1,  6,  8, 11,  3,  7, 12,  4, 14]), om))



[ 0 11 13  5 10  3  2  6  8  9  1  7 12  4 14]
[413]
[401]


In [2]:

om = np.array([
[0,7,8,4,8,7,7,6,9,7,6,6],
[3,0,6,3,4,3,5,3,5,6,4,3],
[2,4,0,4,5,4,5,5,3,7,7,3],
[6,7,6,0,7,7,8,6,7,9,7,5],
[2,6,5,3,0,5,6,4,6,6,6,4],
[3,7,6,3,5,0,6,5,6,7,7,5],
[3,5,5,2,4,4,0,4,6,5,4,3],
[4,7,5,4,6,5,6,0,5,5,6,5],
[1,5,7,3,4,4,4,5,0,6,4,4],
[3,4,3,1,4,3,5,5,4,0,3,4],
[4,6,3,3,4,3,6,4,6,7,0,5],
[4,7,7,5,6,5,7,5,6,6,5,0]])

np.set_printoptions(threshold=sys.maxsize)
algorithm = am0.AzziniMunda0(om) 
start_time = time.time()
sol = algorithm.execute()
t = (time.time() - start_time)
print(t)
#print(sol)
result = np.array([sol.shape[0], algorithm.ntentative], dtype=np.dtype(object))
print(result)

NameError: name 'np' is not defined

In [3]:
om = np.array([
[0,7,8,4,8,7,7,6,9,7,6,6],
[3,0,6,3,4,3,5,3,5,6,4,3],
[2,4,0,4,5,4,5,5,3,7,7,3],
[6,7,6,0,7,7,8,6,7,9,7,5],
[2,6,5,3,0,5,6,4,6,6,6,4],
[3,7,6,3,5,0,6,5,6,7,7,5],
[3,5,5,2,4,4,0,4,6,5,4,3],
[4,7,5,4,6,5,6,0,5,5,6,5],
[1,5,7,3,4,4,4,5,0,6,4,4],
[3,4,3,1,4,3,5,5,4,0,3,4],
[4,6,3,3,4,3,6,4,6,7,0,5],
[4,7,7,5,6,5,7,5,6,6,5,0]])

algorithm = am0.AzziniMunda0(om) 
start_time = time.time()
sol = algorithm.execute()
t = (time.time() - start_time)
print(t)
print(sol)
result = np.array([sol.shape[0], algorithm.ntentative], dtype=np.dtype(object))
print(result)

algorithm = am1.AzziniMunda1(om) 
start_time = time.time()
sol = algorithm.execute()
t = (time.time() - start_time)
print(t)
print(sol)
result = np.array([sol.shape[0], algorithm.ntentative], dtype=np.dtype(object))
print(result)

algorithm = am2.AzziniMunda2(om) 
start_time = time.time()
sol = algorithm.execute()
t = (time.time() - start_time)
print(t)
print(sol)
result = np.array([sol.shape[0], algorithm.ntentative], dtype=np.dtype(object))
print(result)

algorithm = am3.AzziniMunda3(om, np.float('inf')) 
start_time = time.time()
sol = algorithm.execute()
t = (time.time() - start_time)
print(t)
print(sol)
result = np.array([sol.shape[0], algorithm.ntentative], dtype=np.dtype(object))
print(result)

30.579323053359985
[[ 1  7 10  0  5  2  8  3  9 11  6  4]
 [ 1  8 10  0  5  2  7  3  9 11  6  4]
 [ 1  9 10  0  5  2  7  3  8 11  6  4]
 [ 1  7 10  0  5  2  8  4  9 11  6  3]
 [ 1  8 10  0  5  2  7  4  9 11  6  3]
 [ 1  9 10  0  5  2  7  4  8 11  6  3]
 [ 1  7 10  0  5  3  8  2  9 11  6  4]
 [ 1  8 10  0  5  3  7  2  9 11  6  4]
 [ 1  9 10  0  5  3  7  2  8 11  6  4]
 [ 1  7 10  0  4  5  8  2  9 11  6  3]
 [ 1  8 10  0  4  5  7  2  9 11  6  3]
 [ 1  9 10  0  4  5  7  2  8 11  6  3]
 [ 1  7 10  0  5  4  8  2  9 11  6  3]
 [ 1  8 10  0  5  4  7  2  9 11  6  3]
 [ 1  9 10  0  5  4  7  2  8 11  6  3]
 [ 1  7 10  0  5  3  8  4  9 11  6  2]
 [ 1  8 10  0  5  3  7  4  9 11  6  2]
 [ 1  9 10  0  5  3  7  4  8 11  6  2]
 [ 1  7 10  0  4  5  8  3  9 11  6  2]
 [ 1  8 10  0  4  5  7  3  9 11  6  2]
 [ 1  9 10  0  4  5  7  3  8 11  6  2]
 [ 1  7 10  0  5  4  8  3  9 11  6  2]
 [ 1  8 10  0  5  4  7  3  9 11  6  2]
 [ 1  9 10  0  5  4  7  3  8 11  6  2]]
[24 198140]
30.69919991493225
[[ 1  7 10  0 

In [5]:
om = np.array([
[0,3,8,4,4,5,4,5,6,5,5,5,6,4],
[7,0,7,4,3,4,4,4,6,5,6,5,5,4],
[2,3,0,2,3,2,2,3,5,4,3,3,3,4],
[6,6,8,0,5,5,6,6,9,5,6,6,7,5],
[6,7,7,5,0,4,6,5,6,5,5,4,6,5],
[5,6,8,5,6,0,6,5,8,5,7,8,6,5],
[6,6,8,4,4,4,0,6,5,5,4,6,5,4],
[5,6,7,4,5,5,4,0,8,6,5,6,6,7],
[4,4,5,1,4,2,5,2,0,4,5,5,5,4],
[5,5,6,5,5,5,5,4,6,0,4,5,6,7],
[5,4,7,4,5,3,6,5,5,6,0,6,7,4],
[5,5,7,4,6,2,4,4,5,5,4,0,5,5],
[4,5,7,3,4,4,5,4,5,4,3,5,0,4],
[6,6,6,5,5,5,6,3,6,3,6,5,6,0]])

algorithm = am3.AzziniMunda3(om, np.float('inf')) 
start_time = time.time()
sol = algorithm.execute()
t = (time.time() - start_time)
print(t)
print(sol)
result = np.array([sol.shape[0], algorithm.ntentative], dtype=np.dtype(object))
print(result)

529.8019149303436
[[ 8  7 13 ... 11 12  6]
 [ 8  7 13 ... 12 11  6]
 [ 8  7 13 ... 11 12  6]
 ...
 [10  9 13 ...  8 12  6]
 [10  9 12 ...  8 11  6]
 [10  9 13 ...  8 11  6]]
[1458 1458]


In [12]:
print(dRP(np.array([3,4,5,1,8,2,0,7,9,6]), om))
print(dRP(np.array([8,2,3,6,7,1,0,5,9,4]), om))

[160]
[160]


In [4]:
om = np.array([
[0,3,3,0,3,0],
[7,0,7,5,5,7],
[7,3,0,2,3,4],
[10,5,8,0,6,7],
[7,5,7,4,0,4],
[10,3,6,3,6,0]])

results11 = np.zeros(0).reshape(0,8)
rep = 15

exec_time = 0
for i in range(rep):
    # Algorithm without Condorcet
    algorithm = am0.AzziniMunda0(om) 
    start_time = time.time()
    sol = algorithm.execute()
    t = (time.time() - start_time)
    exec_time += t
    print(t)
exec_time = exec_time/rep
result = np.array([11, 2, 1, 0, exec_time, sol.shape[1], algorithm.ntentative, "NULL"], dtype=np.dtype(object))
print(result)
results11 = np.vstack((results11, result))
print(sol)

exec_time = 0
for i in range(rep):
    # Algorithm with Condorcet winner
    algorithm = am1.AzziniMunda1(om) 
    start_time = time.time()
    sol = algorithm.execute()
    t = (time.time() - start_time)
    exec_time += t
    print(t)
exec_time = exec_time/rep
result = np.array([11, 2, 1, 1, exec_time, sol.shape[1], algorithm.ntentative, algorithm.cwinner], dtype=np.dtype(object))
print(result)
results11 = np.vstack((results11, result))
print(sol)

exec_time = 0
for i in range(rep):
    # Algorithm with Condorcet winner
    algorithm = am2.AzziniMunda2(om) 
    start_time = time.time()
    sol = algorithm.execute()
    t = (time.time() - start_time)
    exec_time += t
    print(t)
exec_time = exec_time/rep
result = np.array([11, 2, 1, 2, exec_time, sol.shape[1], algorithm.ntentative, algorithm.cwinner], dtype=np.dtype(object))
print(result)
results11 = np.vstack((results11, result))
print(sol)

0.007214069366455078
0.005489349365234375
0.006863117218017578
0.005293846130371094
0.004918098449707031
0.0049381256103515625
0.005132913589477539
0.004786968231201172
0.004841804504394531
0.006578922271728516
0.005087137222290039
0.006093025207519531
0.0061168670654296875
0.004683017730712891
0.004873991012573242
[11 2 1 0 0.005527416865030925 6 6 'NULL']
[[5 0 4 1 3 2]
 [5 1 4 0 3 2]]
0.0054280757904052734
0.004767894744873047
0.004483938217163086
0.004602193832397461
0.004700899124145508
0.004500865936279297
0.005040884017944336
0.004568815231323242
0.005168914794921875
0.004619121551513672
0.00454401969909668
0.005156993865966797
0.005354166030883789
0.005261898040771484
0.004925966262817383
[11 2 1 1 0.004874976476033529 6 6 None]
[[5 0 4 1 3 2]
 [5 1 4 0 3 2]]
0.002531766891479492
0.00228118896484375
0.0022232532501220703
0.0024919509887695312
0.002413034439086914
0.002298116683959961
0.002299785614013672
0.002576112747192383
0.002302885055541992
0.0023980140686035156
0.00235700

In [9]:
sol

array([[5, 0, 4, 1, 3, 2],
       [5, 1, 4, 0, 3, 2]], dtype=uint8)

In [2]:
om = np.array([
[0,0,0,3,0],
[10,0,7,7,7],
[10,3,0,7,6],
[7,3,3,0,3],
[10,3,4,7,0]])
print(condorcet(om))

[4 0 1 3 2]


In [7]:
om = np.array([
[0,4,7,9,5,7,6,7,7,7,8,8,7],
[6,0,5,7,6,9,7,6,7,7,6,7,6],
[3,5,0,5,5,5,4,3,2,6,5,6,9],
[1,3,5,0,4,6,4,5,5,5,3,8,7],
[5,4,5,6,0,6,5,4,7,4,8,5,8],
[3,1,5,4,4,0,3,4,6,4,5,7,7],
[4,3,6,6,5,7,0,6,7,6,6,9,7],
[3,4,7,5,6,6,4,0,7,7,7,8,7],
[3,3,8,5,3,4,3,3,0,5,6,6,7],
[3,3,4,5,6,6,4,3,5,0,5,6,7],
[2,4,5,7,2,5,4,3,4,5,0,7,8],
[2,3,4,2,5,3,1,2,4,4,3,0,7],
[3,4,1,3,2,3,3,3,3,3,2,3,0]])

algorithm = am2.AzziniMunda2(om) 
start_time = time.time()
sol = algorithm.execute()
t = (time.time() - start_time)
print(t)
print(sol)

algorithm = am0.AzziniMunda0(om) 
start_time = time.time()
sol = algorithm.execute()
t = (time.time() - start_time)
print(t)
print(sol)

479.101891040802
[[ 1  0  6  9  4 10  2  3  5  7  8 11 12]
 [ 1  0  6  8  4 10  2  3  5  9  7 11 12]
 [ 1  0  6  9  4 10  2  3  5  8  7 11 12]
 [ 1  0  7  8  4 10  2  3  5  9  6 11 12]
 [ 1  0  7  9  4 10  2  3  5  8  6 11 12]
 [ 1  0  8  7  4 10  2  3  5  9  6 11 12]
 [ 1  0  8 10  5  6  2  3  7  4  9 11 12]
 [ 1  0  9 10  5  6  2  3  7  4  8 11 12]
 [ 1  0 10  9  5  6  2  3  7  4  8 11 12]
 [ 1  0  7  9  5 10  2  3  6  4  8 11 12]
 [ 1  0  8  9  5 10  2  3  6  4  7 11 12]
 [ 1  0  9  8  5 10  2  3  6  4  7 11 12]
 [ 1  0 10  8  5  9  2  3  6  4  7 11 12]
 [ 1  0 10  7  5  8  2  3  9  4  6 11 12]]
963.7056851387024
[[ 1  0  6  9  4 10  2  3  5  7  8 11 12]
 [ 1  0  6  8  4 10  2  3  5  9  7 11 12]
 [ 1  0  6  9  4 10  2  3  5  8  7 11 12]
 [ 1  0  7  8  4 10  2  3  5  9  6 11 12]
 [ 1  0  7  9  4 10  2  3  5  8  6 11 12]
 [ 1  0  8  7  4 10  2  3  5  9  6 11 12]
 [ 1  0  8 10  5  6  2  3  7  4  9 11 12]
 [ 1  0  9 10  5  6  2  3  7  4  8 11 12]
 [ 1  0 10  9  5  6  2  3  7  4  8 11 12

In [6]:
rep = 15
results11 = np.zeros(0).reshape(0,8)

##############################################################
om = np.array([
[0,5,3,5,5,5,4,4,4,4,6],
[5,0,3,4,3,5,7,3,6,5,6],
[7,7,0,10,8,8,8,7,8,8,8],
[5,6,0,0,4,6,4,1,5,4,4],
[5,7,2,6,0,6,4,0,7,4,7],
[5,5,2,4,4,0,4,2,3,6,5],
[6,3,2,6,6,6,0,5,4,4,6],
[6,7,3,9,10,8,5,0,8,5,8],
[6,4,2,5,3,7,6,2,0,7,4],
[6,5,2,6,6,4,6,5,3,0,6],
[4,4,2,6,3,5,4,2,6,4,0]])


for i in range(rep):
    # Algorithm without Condorcet
    algorithm = am0.AzziniMunda0(om) 
    start_time = time.time()
    sol = algorithm.execute()
    t = (time.time() - start_time)
    exec_time += t
    print(t)
exec_time = exec_time/rep
result = np.array([11, 2, 1, 0, exec_time, sol.shape[1], algorithm.ntentative, "NULL"], dtype=np.dtype(object))
print(result)
results11 = np.vstack((results11, result))


for i in range(rep):
    # Algorithm with Condorcet winner
    algorithm = am1.AzziniMunda1(om) 
    start_time = time.time()
    sol = algorithm.execute()
    t = (time.time() - start_time)
    exec_time = t
    print(t)
exec_time = exec_time/rep
result = np.array([11, 2, 1, 1, exec_time, sol.shape[1], algorithm.ntentative, algorithm.cwinner], dtype=np.dtype(object))
print(result)
results11 = np.vstack((results11, result))


for i in range(rep):
    # Algorithm with Condorcet winner
    algorithm = am2.AzziniMunda2(om) 
    start_time = time.time()
    sol = algorithm.execute()
    t = (time.time() - start_time)
    exec_time = t
    print(t)
exec_time = exec_time/rep
result = np.array([11, 2, 1, 1, exec_time, sol.shape[1], algorithm.ntentative, algorithm.cwinner], dtype=np.dtype(object))
print(result)
results11 = np.vstack((results11, result))


array([4, 2, 3, 1])

In [9]:
results8 = np.zeros(0).reshape(0,8)

In [ ]:
om = np.array([
[0,4,6,5,5,5,2,5],
[6,0,4,5,5,3,3,5],
[4,6,0,7,6,5,0,5],
[5,5,3,0,8,5,1,6],
[5,5,4,2,0,4,1,6],
[5,7,5,5,6,0,1,4],
[8,7,10,9,9,9,0,7],
[5,5,5,4,4,6,3,0]])

In [3]:
##############################################################
om = np.array([
[0,4,6,5,5,5,2,5],
[6,0,4,5,5,3,3,5],
[4,6,0,7,6,5,0,5],
[5,5,3,0,8,5,1,6],
[5,5,4,2,0,4,1,6],
[5,7,5,5,6,0,1,4],
[8,7,10,9,9,9,0,7],
[5,5,5,4,4,6,3,0]])

 
rep = 15

for i in range(rep):

    # Algorithm without Condorcet
    algorithm = am0.AzziniMunda0(om) 
    start_time = time.time()
    sol = algorithm.execute()
    t = (time.time() - start_time)
    exec_time += t
    print(t)
exec_time = exec_time/rep
result = np.array([8, 1, 1, 0, exec_time, sol.shape[1], algorithm.ntentative, "NULL"], dtype=np.dtype(object))
print(result)
results8 = np.vstack((results8, result))

for i in range(rep):

    # Algorithm with Condorcet winner
    algorithm = am1.AzziniMunda1(om) 
    start_time = time.time()
    sol = algorithm.execute()
    t = (time.time() - start_time)
    exec_time = t
    print(t)
exec_time = exec_time/rep
result = np.array([8, 1, 1, 1, exec_time, sol.shape[1], algorithm.ntentative, algorithm.cwinner], dtype=np.dtype(object))
print(result)
results8 = np.vstack((results8, result))

##############################################################
om = np.array([
[0,4,6,6,5,6,1,4],
[6,0,4,5,4,7,1,6],
[4,6,0,4,7,3,3,5],
[4,5,6,0,5,4,2,5],
[5,6,3,5,0,5,3,5],
[4,3,7,6,5,0,0,5],
[9,9,7,8,7,10,0,9],
[6,4,5,5,5,5,1,0]])

 
rep = 15

for i in range(rep):

    # Algorithm without Condorcet
    algorithm = am0.AzziniMunda0(om) 
    start_time = time.time()
    sol = algorithm.execute()
    t = (time.time() - start_time)
    exec_time += t
    print(t)
exec_time = exec_time/rep
result = np.array([8, 1, 2, 0, exec_time, sol.shape[1], algorithm.ntentative, "NULL"], dtype=np.dtype(object))
print(result)
results8 = np.vstack((results8, result))


          
for i in range(rep):

    # Algorithm with Condorcet winner
    algorithm = am1.AzziniMunda1(om) 
    start_time = time.time()
    sol = algorithm.execute()
    t = (time.time() - start_time)
    exec_time = t
    print(t)
exec_time = exec_time/rep
result = np.array([8, 1, 2, 1, exec_time, sol.shape[1], algorithm.ntentative, algorithm.cwinner], dtype=np.dtype(object))
print(result)
results8 = np.vstack((results8, result))

##############################################################
om = np.array([
[0,4,2,4,2,5,3,6],
[6,0,7,4,2,5,4,4],
[8,3,0,3,3,5,3,6],
[6,6,7,0,1,4,6,3],
[8,8,7,9,0,8,9,9],
[5,5,5,6,2,0,5,5],
[7,6,7,4,1,5,0,4],
[4,6,4,7,1,5,6,0]])

 
rep = 15

for i in range(rep):

    # Algorithm without Condorcet
    algorithm = am0.AzziniMunda0(om) 
    start_time = time.time()
    sol = algorithm.execute()
    t = (time.time() - start_time)
    exec_time += t
    print(t)
exec_time = exec_time/rep
result = np.array([8, 1, 3, 0, exec_time, sol.shape[1], algorithm.ntentative, "NULL"], dtype=np.dtype(object))
print(result)
results8 = np.vstack((results8, result))


          
for i in range(rep):

    # Algorithm with Condorcet winner
    algorithm = am1.AzziniMunda1(om) 
    start_time = time.time()
    sol = algorithm.execute()
    t = (time.time() - start_time)
    exec_time = t
    print(t)
exec_time = exec_time/rep
result = np.array([8, 1, 3, 1, exec_time, sol.shape[1], algorithm.ntentative, algorithm.cwinner], dtype=np.dtype(object))
print(result)
results8 = np.vstack((results8, result))

##############################################################
om = np.array([
[0,5,5,7,4,4,5,4],
[5,0,5,6,4,5,6,2],
[5,5,0,4,6,3,5,3],
[3,4,6,0,5,6,6,3],
[6,6,4,5,0,7,4,2],
[6,5,7,4,3,0,5,2],
[5,4,5,4,6,5,0,2],
[6,8,7,7,8,8,8,0]])

 
rep = 15

for i in range(rep):

    # Algorithm without Condorcet
    algorithm = am0.AzziniMunda0(om) 
    start_time = time.time()
    sol = algorithm.execute()
    t = (time.time() - start_time)
    exec_time += t
    print(t)
exec_time = exec_time/rep
result = np.array([8, 1, 4, 0, exec_time, sol.shape[1], algorithm.ntentative, "NULL"], dtype=np.dtype(object))
print(result)
results8 = np.vstack((results8, result))


          
for i in range(rep):

    # Algorithm with Condorcet winner
    algorithm = am1.AzziniMunda1(om) 
    start_time = time.time()
    sol = algorithm.execute()
    t = (time.time() - start_time)
    exec_time = t
    print(t)
exec_time = exec_time/rep
result = np.array([8, 1, 4, 1, exec_time, sol.shape[1], algorithm.ntentative, algorithm.cwinner], dtype=np.dtype(object))
print(result)
results8 = np.vstack((results8, result))


0.025683879852294922
0.023647069931030273
0.018759727478027344
0.017817258834838867
0.017323970794677734
0.01784968376159668
0.017528057098388672
0.017452239990234375
0.017467737197875977
0.01871514320373535
0.017989158630371094
0.018342971801757812
0.01865410804748535
0.018361806869506836
0.01766490936279297
[8 1 1 0 0.7615272998809814 8 143 'NULL']


NameError: name 'results8' is not defined

In [2]:
om = np.array([
[0,3,3,0,3,0],
[7,0,7,5,5,7],
[7,3,0,2,3,4],
[10,5,8,0,6,7],
[7,5,7,4,0,4],
[10,3,6,3,6,0]])
algorithm = am0.AzziniMunda0(om) 
start_time = time.time()
sol = algorithm.execute()
exec_time = (time.time() - start_time)
print(exec_time)
print(sol)
print("#####")
algorithm = am3.AzziniMunda3(om, np.float('inf')) 
start_time = time.time()
sol = algorithm.execute()
exec_time = (time.time() - start_time)
print(exec_time)
print(sol)


0.01822185516357422
[[5 0 4 1 3 2]
 [5 1 4 0 3 2]]
#####
0.004266977310180664
[[5 0 4 1 3 2]
 [5 1 4 0 3 2]]


In [5]:
print(om)
print(om[:,0])

[[ 0  3  7  3  7  3  3  7  7  7  3  3]
 [ 7  0  4  0  7  7  3  4  4  7  4  4]
 [ 3  6  0  0  7  6  6  3  0  3  6  0]
 [ 7 10 10  0  7 10 10  7 10 10 10  7]
 [ 3  3  3  3  0  6  6  3  3  6  3  3]
 [ 7  3  4  0  4  0  3  7  4  4  7  0]
 [ 7  7  4  0  4  7  0  4  4  4  4  4]
 [ 3  6  7  3  7  3  6  0  3  3  6  3]
 [ 3  6 10  0  7  6  6  7  0  3  6  0]
 [ 3  3  7  0  4  6  6  7  7  0  3  0]
 [ 7  6  4  0  7  3  6  4  4  7  0  0]
 [ 7  6 10  3  7 10  6  7 10 10 10  0]]
[0 7 3 7 3 7 7 3 3 3 7 7]


In [6]:
st = time.time()
condorcet(om)
print(time.time()-st)

0.0006349086761474609


In [3]:
cache = dict()
cache["noelia"] = np.array([3, 2, 1])

In [5]:
cache["noelia"]

array([3, 2, 1])

In [27]:
to_explore = np.ones(14, dtype=bool)

In [28]:
to_explore[3] = 0
to_explore[1] = 0

In [29]:
to_explore

array([ True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [30]:
np.array2string(1*to_explore, separator="", prefix="")

'[10101111111111]'

In [21]:
om = np.array([
[0,3,3,0,3,0],
[7,0,7,5,5,7],
[7,3,0,2,3,4],
[10,5,8,0,6,7],
[7,5,7,4,0,4],
[10,3,6,3,6,0]])
print(om > 5)
st = time.time()
a = (np.sum((om > 5), axis = 1) == 4).nonzero()[0].astype(int)
print(time.time() - st)
print(a)

[[False False False False False False]
 [ True False  True False False  True]
 [ True False False False False False]
 [ True False  True False  True  True]
 [ True False  True False False False]
 [ True False  True False  True False]]
0.0019390583038330078
[3]


In [35]:
st = time.time()
(om > 5).sum()
print(time.time() - st)

0.00022602081298828125


In [27]:
print(om)
keep = [True, False, False, True, False, False]
om[keep,:][:,keep]

[[ 0  3  3  0  3  0]
 [ 7  0  7  5  5  7]
 [ 7  3  0  2  3  4]
 [10  5  8  0  6  7]
 [ 7  5  7  4  0  4]
 [10  3  6  3  6  0]]


array([[ 0,  0],
       [10,  0]])

In [76]:
om = np.array([
[0,3,3,0,3,0],
[7,0,7,5,5,7],
[7,3,0,2,3,4],
[10,5,8,0,6,7],
[7,5,7,4,0,4],
[10,3,6,3,6,0]])
b = om > 5
print(b)
keep = [True, True, True, True, True, True]
st = time.time()
a = (np.sum(b[keep,:][:,keep], axis = 1) == 10).nonzero()[0]
print(time.time() - st)
print(a)

[[False False False False False False]
 [ True False  True False False  True]
 [ True False False False False False]
 [ True False  True False  True  True]
 [ True False  True False False False]
 [ True False  True False  True False]]
0.00030684471130371094
[]


In [77]:
if a.size == 0:
    print("si")

si


In [64]:
a

array([3])