In [1]:
import numpy as np
from scf.borda import *
from scf.distance import *
import scf.initialization as init
from dfs.dfs1 import dfs1
import time

Loading scf


# n = 8

n = 10

- 1 - C6 - 1 - 4.39
- 2 - C3 - 1 - 16
- 3 - C0 - 1 - 4.55 
- 4 - C5 - 5 - 5.85
- 5 - C4 - 3 - 4.26
- 6 - C5 - 6 - 9.59
- 7 - C8 - 4 - 7.7
- 8 - C3 - 1 - 10.8
- 9 - C4 - 1 - 4.65
- 10 - C7 - 2 - 5.85


- seed - winners - time - nrankings sol - incertidumbre1 - incertidumbre2
- 1 - C5       - 237 - 3 - 0.625 - 0.694
- 2 - C0,C1,C4 - 416 - 3 - 0.5   - 0.694 
- 3 - C5       - 319 - 1 - 0.375 - 0.666 
- 4 - C2,C6    - 284 - 6 - 0.5   - 0.666
- 5 - C7       - 407 - 0.72
- 6 - C4 - 447
- 7 - C4 - 228
- 8 - C0 - 210
- 9 - C0 - 381




In [2]:
def measure(n, seed, rep = 3, om = None):
    
    # n
    # seed
    # incertidumbre1
    # incertidumbre2
    # incertidumbre3
    # incertidumbre4
    # incertidumbre5
    # hay que mirar tb la media 
    # RESULTS full
    # RESULTS borda
    # Kemeny distance
    # Borda distance
    # winners
    
    if om is None:
        np.random.seed(seed)
        om = init.create_random_om(n, 10) 
    else:
        seed = None
    
    results = np.array([n, seed])
    results = np.append(results, [
               incertidumbre1(om),
               incertidumbre2(om),
               incertidumbre3(om),
               incertidumbre4(om),
               incertidumbre5(om)])
    
    # The first time is slower because it need to be compile so do it random
    np.random.seed(123)
    compileom = init.create_random_om(4, 10) 
    dfs1(compileom, float('inf'))
    ##########################################################################
      
    print("Execution without init...")    
    # Execution time without init distance ###################################
    extime = 0
    for i in range(rep):
        start = time.time()
        sol1 = dfs1(om, float('inf'))
        end = time.time()
        extime += (end-start)
    print(extime/rep)
    results = np.append(results, extime/rep) 
    print(sol1)
    
    a = np.arange(om.shape[0]).tolist() # the ranking
    b = sol1[0].tolist() # the indexes
    sol = np.array([b.index(x) if x in b else None for x in a])
    dk = dRP(sol, om)
    print("Obtained distance is {}".format(dk))
    print(sol)
    
    # Calculate borda count and the distance to the profile
    r = ranking_to_lineal(borda(om))
    db = dRP(r, om)
    print("Execution with borda... (distance = {})".format(db))
    print(r)
    #print(b)
    # Execution time using the distance given by Borda Count
    extime = 0
    for i in range(rep):
        start = time.time()
        sol2 = dfs1(om, db)
        end = time.time()
        extime += (end-start)
    print(extime/rep)
    print(sol2)
    results = np.append(results, extime/rep)
    results = np.append(results, [dk, db])
    results = np.append(results, np.array2string(sol2[:,0]))
    
    return results
    

In [81]:
results4 = np.zeros(0).reshape(0,12)
for i in range(12,13):
    print("#########################################")
    print("#########################################")
    print("##N{}####################################".format(i))
    for j in range(7,15):
        print("j = {} -------------------------------------------------------".format(j))
        results4 = np.vstack((results4, measure(i,j,rep=1)))
        #np.random.seed(j)
        #om = init.create_random_om(i, 10) 
        #print(om)

#########################################
#########################################
##N12####################################
j = 7 -------------------------------------------------------
Execution without init...
208.25558495521545
[[ 6 10  0  9  5  8  2 11  3  7  4  1]]
Obtained distance is [222]
[ 2 11  6  8 10  4  0  9  5  3  1  7]
Execution without borda... (distance = [264])
[ 1 11  2  9 10  5  3  6  4  7  0  8]
198.81345200538635
[[ 6 10  0  9  5  8  2 11  3  7  4  1]]
j = 8 -------------------------------------------------------
Execution without init...
327.14417791366577
[[ 2  8  4  9  1  7  3 11  5  6 10  0]]
Obtained distance is [235]
[11  4  0  6  2  8  9  5  1  3 10  7]
Execution without borda... (distance = [279])
[11  2  1  3  8  9  6  5  0  4  7 10]
326.03520011901855
[[ 2  8  4  9  1  7  3 11  5  6 10  0]]
j = 9 -------------------------------------------------------
Execution without init...
286.26802682876587
[[ 1  9  5 11  3  0  8  4  2 10  7  6]
 [ 5  1  9 11  3  

In [296]:
a = np.arange(5).tolist() # the indexes
b = np.array([4,0,1,3,2]).tolist() # the ranking
[b.index(x) if x in b else None for x in a]

[1, 2, 4, 3, 0]

In [60]:
results2

array([['11.0', '5.0', '6.0', '51.0', '426.0', '5.333333333333333',
        '32.16666666666667', '18.442365407943726', '15.740551948547363',
        '166.0', '196.0', '[4]'],
       ['11.0', '6.0', '4.0', '45.0', '405.0', '4.7', '27.8',
        '53.069825649261475', '50.88697695732117', '189.0', '211.0',
        '[9 9 9 9]'],
       ['11.0', '7.0', '5.0', '52.0', '418.0', '3.833333333333333',
        '26.0', '23.151739676793415', '22.84928290049235', '170.0',
        '212.0', '[1]'],
       ['11.0', '8.0', '6.0', '48.0', '400.0', '3.833333333333333',
        '19.833333333333332', '43.20329634348551', '42.51522866884867',
        '186.0', '198.0', '[2 2 8 8]'],
       ['11.0', '9.0', '6.0', '50.0', '411.0', '6.833333333333334',
        '39.0', '35.06697130203247', '33.64926481246948', '169.0',
        '201.0', '[7 7]']], dtype='<U32')

In [71]:
results3

array([['12.0', '1.0', '5.0', '62.0', '507.0', '4.833333333333334',
        '29.5', '167.6790108680725', '162.5059530735016', '213.0',
        '253.0', '[6]'],
       ['12.0', '2.0', '5.0', '61.0', '488.0', '2.5833333333333335',
        '14.583333333333334', '358.10959792137146', '356.90887212753296',
        '238.0', '268.0', '[1]']], dtype='<U32')

In [57]:
import pandas as pd

In [82]:
pd.DataFrame(results4).to_csv("results4_kemeny.csv")

In [3]:
def incertidumbre1(om): # number of alternatives that would be explored with azzini   
    return np.sum(om.sum(axis=1) >= om.sum(axis=0)) # / om.shape[0]
def incertidumbre2(om): # sum in relation to condorcet   
    return ((om > 5).sum(axis=1)).sum() # / (((n)*(n+1))/2)
def incertidumbre3(om): # for each pair keep the max
    values = om[np.triu_indices(om.shape[0], k = 1)]
    votes = om[0,1]+om[1,0]
    #print(np.maximum(votes-values, values))
    return np.sum(np.maximum(votes-values, values))
def incertidumbre4(om): # ponderando por los puestos que acierta
    votes = om[0,1]+om[1,0]
    ranking = (om > 5).sum(axis=1)
    #print(votes)
    #print(ranking)
    count = 0
    for i in range(1,om.shape[0]+1):
        are = np.where(ranking == (i-1))[0]
        if are.size >= 1:
            #print("i = {}, adding {}".format(i-1, i /are.size))
            count += 1 / are.size
    return count
def incertidumbre5(om): # ponderando por los puestos que acierta
    votes = om[0,1]+om[1,0]
    ranking = (om > 5).sum(axis=1)
    #print(votes)
    #print(ranking)
    count = 0
    for i in range(1,om.shape[0]+1):
        are = np.where(ranking == (i-1))[0]
        if are.size >= 1:
            #print("i = {}, adding {}".format(i-1, i /are.size))
            count += i / are.size
    return count

In [206]:
n = 4
np.random.seed(1)
om = init.create_random_om(n, 10) 
print(om)
print(incertidumbre4(om))

[[ 0  9  5  0]
 [ 1  0  5  0]
 [ 5  5  0  8]
 [10 10  2  0]]
2.5


In [145]:
incertidumbre4(om)

10
[2 3 4 4 3 6 2 1]
1
2
3
4
5
6
7
8


In [113]:
print(om)
incertidumbre3(om)

[[ 0  5  7  6  7  1  0  5]
 [ 5  0  7  1  2  7  8  6]
 [ 3  3  0  9  1  0  9  4]
 [ 4  9  1  0  9  6  9  0]
 [ 3  8  9  1  0  2  0  9]
 [ 9  3 10  4  8  0  4  3]
 [10  2  1  1 10  6  0  0]
 [ 5  4  6 10  1  7 10  0]]
[ 5  7  6  7  9 10  5  7  9  8  7  8  6  9  9 10  9  6  9  6  9 10  8 10
  9  6  7 10]


221

In [81]:
res

''

# n = 9

In [4]:
om = np.array([
[0,3,6,4,8,6,4,6],
[7,0,5,6,7,4,5,5],
[4,5,0,5,6,7,7,5],
[6,4,5,0,7,6,5,6],
[2,3,4,3,0,5,3,4],
[4,6,3,4,5,0,3,6],
[6,5,3,5,7,7,0,6],
[4,5,5,4,6,4,4,0]])
b = borda(om)
dfs1.kemeny2(om, float('inf'))

solution is (114, array([1, 2, 3, 6, 0, 5, 7, 4], dtype=int32))


array([[1, 2, 3, 6, 0, 5, 7, 4]], dtype=int32)

# n = 12

In [70]:
om = np.array([
[0,4,4,2,2,6,3,2,3,3,6,3],
[6,0,6,0,3,6,3,5,5,6,6,5],
[6,4,0,2,3,4,4,3,3,6,4,2],
[8,10,8,0,6,8,5,7,7,7,6,6],
[8,7,7,4,0,8,5,6,5,5,7,7],
[4,4,6,2,2,0,5,2,3,5,5,4],
[7,7,6,5,5,5,0,6,6,6,5,5],
[8,5,7,3,4,8,4,0,3,5,6,6],
[7,5,7,3,5,7,4,7,0,7,6,5],
[7,4,4,3,5,5,4,5,3,0,5,4],
[4,4,6,4,3,5,5,4,4,5,0,6],
[7,5,8,4,3,6,5,4,5,6,4,0]])

bc = np.array([11,6,10,0,1,9,2,4,3,8,7,5])
d = dRP(bc, om)

measure(12,1,rep=1,om=om)

Execution without init...
1020.0581932067871
[[ 3  4  6  1  8  7 10 11  2  9  0  5]
 [ 3  4  6  1  8  7 10 11  5  2  9  0]
 [ 3  4  6  8  1  7 10 11  2  9  0  5]
 [ 3  4  6  8  1  7 10 11  5  2  9  0]
 [ 3  4  6  8  7  1 10 11  2  9  0  5]
 [ 3  4  6  8  7  1 10 11  5  2  9  0]
 [ 3  6  4  1  8  7 10 11  2  9  0  5]
 [ 3  6  4  1  8  7 10 11  5  2  9  0]
 [ 3  6  4  8  1  7 10 11  2  9  0  5]
 [ 3  6  4  8  1  7 10 11  5  2  9  0]
 [ 3  6  4  8  7  1 10 11  2  9  0  5]
 [ 3  6  4  8  7  1 10 11  5  2  9  0]
 [ 3  6  8  4  1  7 10 11  2  9  0  5]
 [ 3  6  8  4  1  7 10 11  5  2  9  0]
 [ 3  6  8  4  7  1 10 11  2  9  0  5]
 [ 3  6  8  4  7  1 10 11  5  2  9  0]
 [ 6  3  4  1  8  7 10 11  2  9  0  5]
 [ 6  3  4  1  8  7 10 11  5  2  9  0]
 [ 6  3  4  8  1  7 10 11  2  9  0  5]
 [ 6  3  4  8  1  7 10 11  5  2  9  0]
 [ 6  3  4  8  7  1 10 11  2  9  0  5]
 [ 6  3  4  8  7  1 10 11  5  2  9  0]
 [ 6  3  8  4  1  7 10 11  2  9  0  5]
 [ 6  3  8  4  1  7 10 11  5  2  9  0]
 [ 6  3  8  4  7  1

array(['12.0', '1.0', '6.0', '51.0', '418.0', '4.833333333333333', '32.5',
       '1020.0581932067871', '740.4536447525024', '246.0', '250.0',
       '[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 6 6 6 6 6 6 6 6 6 6]'],
      dtype='<U53')

In [ ]:
om = np.array([
[0,3,6,4,8,6,4,6],
[7,0,5,6,7,4,5,5],
[4,5,0,5,6,7,7,5],
[6,4,5,0,7,6,5,6],
[2,3,4,3,0,5,3,4],
[4,6,3,4,5,0,3,6],
[6,5,3,5,7,7,0,6],
[4,5,5,4,6,4,4,0]])

In [83]:
om = np.array([
[0,5,4,3,4,6,6,8,7,1,2,4],
[5,0,4,3,6,8,8,7,5,4,4,5],
[6,6,0,5,7,6,7,8,7,3,5,5],
[7,7,5,0,8,7,8,7,8,6,5,7],
[6,4,3,2,0,5,6,6,4,2,2,4],
[4,2,4,3,5,0,8,6,6,2,4,4],
[4,2,3,2,4,2,0,5,4,1,2,1],
[2,3,2,3,4,4,5,0,5,2,2,3],
[3,5,3,2,6,4,6,5,0,2,1,4],
[9,6,7,4,8,8,9,8,8,0,5,6],
[8,6,5,5,8,6,8,8,9,5,0,4],
[6,5,5,3,6,6,9,7,6,4,6,0]])
measure(12,1,rep=1,om=om)

Execution without init...
394.64833998680115
[[ 3  9  2 11 10  0  1  5  8  4  6  7]
 [ 3  9  2 11 10  0  1  5  8  4  7  6]
 [ 3  9  2 11 10  1  0  5  8  4  6  7]
 [ 3  9  2 11 10  1  0  5  8  4  7  6]
 [ 3  9  2 11 10  1  4  0  5  7  8  6]
 [ 3  9  2 11 10  1  4  0  5  8  6  7]
 [ 3  9  2 11 10  1  4  0  5  8  7  6]
 [ 3  9 11  2 10  0  1  5  8  4  6  7]
 [ 3  9 11  2 10  0  1  5  8  4  7  6]
 [ 3  9 11  2 10  1  0  5  8  4  6  7]
 [ 3  9 11  2 10  1  0  5  8  4  7  6]
 [ 3  9 11  2 10  1  4  0  5  7  8  6]
 [ 3  9 11  2 10  1  4  0  5  8  6  7]
 [ 3  9 11  2 10  1  4  0  5  8  7  6]
 [ 3  9 11 10  2  0  1  5  8  4  6  7]
 [ 3  9 11 10  2  0  1  5  8  4  7  6]
 [ 3  9 11 10  2  1  0  5  8  4  6  7]
 [ 3  9 11 10  2  1  0  5  8  4  7  6]
 [ 3  9 11 10  2  1  4  0  5  7  8  6]
 [ 3  9 11 10  2  1  4  0  5  8  6  7]
 [ 3  9 11 10  2  1  4  0  5  8  7  6]]
Obtained distance is [221]
[ 5  6  2  0  9  7 10 11  8  1  4  3]
Execution without borda... (distance = [227])
[ 6  5  3  1  8  7 11 10

array([12, None, 6.0, 55.0, 441.0, 3.3333333333333335, 15.666666666666666,
       394.64833998680115, 332.84674191474915, 221, 227,
       '[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]'], dtype=object)

In [85]:
om = np.array([
[0,2,4,2,6,3,5,4,7,4,4,5],
[8,0,4,6,6,8,7,5,7,4,5,7],
[6,6,0,3,7,6,7,5,7,5,2,6],
[8,4,7,0,8,8,7,6,7,6,6,8],
[4,4,3,2,0,5,7,3,6,3,2,5],
[7,2,4,2,5,0,6,4,6,4,4,6],
[5,3,3,3,3,4,0,5,3,4,3,4],
[6,5,5,4,7,6,5,0,5,5,4,6],
[3,3,3,3,4,4,7,5,0,5,4,5],
[6,6,5,4,7,6,6,5,5,0,4,5],
[6,5,8,4,8,6,7,6,6,6,0,8],
[5,3,4,2,5,4,6,4,5,5,2,0]])
measure(12,1,rep=1,om=om)

Execution without init...
811.932361125946
[[ 3 10  2  7  9  1  5  0  4  8 11  6]
 [ 3 10  2  7  9  1  5  0  4 11  8  6]
 [ 3 10  2  7  9  1  5  0 11  4  8  6]
 [ 3 10  2  7  9  1  5 11  0  4  8  6]
 [ 3 10  2  9  1  7  5  0  4  8 11  6]
 [ 3 10  2  9  1  7  5  0  4 11  8  6]
 [ 3 10  2  9  1  7  5  0 11  4  8  6]
 [ 3 10  2  9  1  7  5 11  0  4  8  6]
 [ 3 10  2  9  7  1  5  0  4  8 11  6]
 [ 3 10  2  9  7  1  5  0  4 11  8  6]
 [ 3 10  2  9  7  1  5  0 11  4  8  6]
 [ 3 10  2  9  7  1  5 11  0  4  8  6]
 [ 3 10  7  2  9  1  5  0  4  8 11  6]
 [ 3 10  7  2  9  1  5  0  4 11  8  6]
 [ 3 10  7  2  9  1  5  0 11  4  8  6]
 [ 3 10  7  2  9  1  5 11  0  4  8  6]
 [ 3 10  7  9  2  1  5  0  4  8 11  6]
 [ 3 10  7  9  2  1  5  0  4 11  8  6]
 [ 3 10  7  9  2  1  5  0 11  4  8  6]
 [ 3 10  7  9  2  1  5 11  0  4  8  6]
 [ 3 10  9  2  1  7  5  0  4  8 11  6]
 [ 3 10  9  2  1  7  5  0  4 11  8  6]
 [ 3 10  9  2  1  7  5  0 11  4  8  6]
 [ 3 10  9  2  1  7  5 11  0  4  8  6]
 [ 3 10  9  2  7  1  

array([12, None, 6.0, 52.0, 416.0, 6.0, 37.0, 811.932361125946,
       701.852814912796, 246, 252,
       '[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]'],
      dtype=object)

In [86]:
om = np.array([
[0,10,7,7,7,7,10,7,7,7,7,7],
[0,0,0,0,0,0,3,0,0,0,0,0],
[3,10,0,6,7,3,7,7,10,7,6,7],
[3,10,4,0,7,7,7,4,7,7,0,4],
[3,10,3,3,0,3,6,7,7,3,3,4],
[3,10,7,3,7,0,7,4,7,4,3,4],
[0,7,3,3,4,3,0,4,7,4,3,4],
[3,10,3,6,3,6,6,0,10,3,6,7],
[3,10,0,3,3,3,3,0,0,3,3,7],
[3,10,3,3,7,6,6,7,7,0,3,4],
[3,10,4,10,7,7,7,4,7,7,0,7],
[3,10,3,6,6,6,6,3,3,6,3,0]])
measure(12,1,rep=1,om=om)

Execution without init...
74.94581890106201
[[ 0  2  7 10 11  3  9  5  4  6  8  1]]
Obtained distance is [186]
[ 0 11  1  5  8  7  9  2 10  6  3  4]
Execution without borda... (distance = [196])
[ 0 11  1  4  8  5  9  3 10  6  2  7]
59.071969985961914
[[ 0  2  7 10 11  3  9  5  4  6  8  1]]


array([12, None, 8.0, 66.0, 490.0, 7.833333333333334, 54.833333333333336,
       74.94581890106201, 59.071969985961914, 186, 196, '[0]'],
      dtype=object)

In [87]:
om = np.array([
[0,7,6,7,6,6,7,4,6,5,5,5],
[3,0,3,7,6,4,5,3,3,6,4,4],
[4,7,0,5,5,6,5,3,5,6,6,6],
[3,3,5,0,4,4,3,1,3,4,5,5],
[4,4,5,6,0,6,4,3,3,6,6,5],
[4,6,4,6,4,0,4,3,5,6,6,5],
[3,5,5,7,6,6,0,2,4,5,6,7],
[6,7,7,9,7,7,8,0,6,8,7,8],
[4,7,5,7,7,5,6,4,0,9,6,5],
[5,4,4,6,4,4,5,2,1,0,3,4],
[5,6,4,5,4,4,4,3,4,7,0,6],
[5,6,4,5,5,5,3,2,5,6,4,0]])
measure(12,1,rep=1,om=om)

Execution without init...
1009.2374558448792
[[ 7  0  2  8  6  4  5 10 11  1  9  3]
 [ 7  0  8  2  6  4  5 10 11  1  9  3]
 [ 7  0  8  6  2  4  5 10 11  1  9  3]
 [ 7  0  8  6  4  2  5 10 11  1  9  3]]
Obtained distance is [253]
[ 1  9  2 11  5  6  4  0  3 10  7  8]
Execution without borda... (distance = [257])
[ 2  9  3 11  6  5  4  0  1 10  7  8]
985.0502760410309
[[ 7  0  2  8  6  4  5 10 11  1  9  3]
 [ 7  0  8  2  6  4  5 10 11  1  9  3]
 [ 7  0  8  6  2  4  5 10 11  1  9  3]
 [ 7  0  8  6  4  2  5 10 11  1  9  3]]


array([12, None, 5.0, 51.0, 409.0, 7.5, 40.5, 1009.2374558448792,
       985.0502760410309, 253, 257, '[7 7 7 7]'], dtype=object)

In [88]:
om = np.array([
[0,4,2,4,3,4,4,4,4,5,4,3],
[6,0,6,4,6,5,5,5,3,8,7,5],
[8,4,0,5,6,6,9,6,6,7,8,6],
[6,6,5,0,9,6,7,6,5,8,5,6],
[7,4,4,1,0,3,5,3,2,6,5,4],
[6,5,4,4,7,0,4,4,3,7,6,4],
[6,5,1,3,5,6,0,4,6,6,5,4],
[6,5,4,4,7,6,6,0,5,8,6,6],
[6,7,4,5,8,7,4,5,0,8,5,5],
[5,2,3,2,4,3,4,2,2,0,5,3],
[6,3,2,5,5,4,5,4,5,5,0,5],
[7,5,4,4,6,6,6,4,5,7,5,0]])
measure(12,1,rep=1,om=om)

Execution without init...
1039.054109096527
[[ 2  3  7 11  6  8  1  5  4  9 10  0]
 [ 2  3  7 11  6  8  1  5  4 10  0  9]
 [ 2  3  7 11  6  8  1  5  4 10  9  0]
 [ 2  3  7 11  6  8  1  5 10  4  0  9]
 [ 2  3  7 11  6  8  1  5 10  4  9  0]
 [ 2  3  7 11  6  8  5  1  4  9 10  0]
 [ 2  3  7 11  6  8  5  1  4 10  0  9]
 [ 2  3  7 11  6  8  5  1  4 10  9  0]
 [ 2  3  7 11  6  8  5  1 10  4  0  9]
 [ 2  3  7 11  6  8  5  1 10  4  9  0]
 [ 3  2  7 11  6  8  1  5  4  9 10  0]
 [ 3  2  7 11  6  8  1  5  4 10  0  9]
 [ 3  2  7 11  6  8  1  5  4 10  9  0]
 [ 3  2  7 11  6  8  1  5 10  4  0  9]
 [ 3  2  7 11  6  8  1  5 10  4  9  0]
 [ 3  2  7 11  6  8  5  1  4  9 10  0]
 [ 3  2  7 11  6  8  5  1  4 10  0  9]
 [ 3  2  7 11  6  8  5  1  4 10  9  0]
 [ 3  2  7 11  6  8  5  1 10  4  0  9]
 [ 3  2  7 11  6  8  5  1 10  4  9  0]]
Obtained distance is [251]
[11  6  0  1  8  7  4  2  5  9 10  3]
Execution without borda... (distance = [255])
[10  4  0  1  9  6  7  3  2 11  8  5]
902.1197497844696
[[ 2  3 

array([12, None, 6.0, 50.0, 411.0, 6.333333333333334, 37.0,
       1039.054109096527, 902.1197497844696, 251, 255,
       '[2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3]'], dtype=object)

In [92]:
om = np.array([
[0,3,3,3,5,3,3,4,5,2,2,3],
[7,0,6,7,7,7,3,4,3,4,3,4],
[7,4,0,5,6,4,5,6,4,5,4,5],
[7,3,5,0,7,6,5,7,5,6,3,5],
[5,3,4,3,0,4,4,4,1,3,1,3],
[7,3,6,4,6,0,6,5,6,4,3,4],
[7,7,5,5,6,4,0,5,4,4,2,6],
[6,6,4,3,6,5,5,0,4,4,3,5],
[5,7,6,5,9,4,6,6,0,6,4,6],
[8,6,5,4,7,6,6,6,4,0,3,5],
[8,7,6,7,9,7,8,7,6,7,0,7],
[7,6,5,5,7,6,4,5,4,5,3,0]])
measure(12,1,rep=1,om=om)

Execution without init...
1693.8086919784546
[[10  8  9  6 11  1  3  5  2  7  0  4]
 [10  8  9  6 11  1  3  5  2  7  4  0]]
Obtained distance is [252]
[10  5  8  6 11  7  3  9  1  2  0  4]
Execution without borda... (distance = [264])
[10  5  6  3 11  8  7  9  1  2  0  4]
1351.1943359375
[[10  8  9  6 11  1  3  5  2  7  0  4]
 [10  8  9  6 11  1  3  5  2  7  4  0]]


array([12, None, 8.0, 53.0, 416.0, 4.833333333333333, 34.0,
       1693.8086919784546, 1351.1943359375, 252, 264, '[10 10]'],
      dtype=object)

In [93]:
om = np.array([
[0,4,4,5,4,4,4,4,3,4,4,3],
[6,0,6,6,5,5,7,5,6,6,8,7],
[6,4,0,4,5,5,5,4,4,3,4,4],
[5,4,6,0,4,7,3,7,5,4,4,5],
[6,5,5,6,0,5,7,6,5,4,5,5],
[6,5,5,3,5,0,5,3,4,4,4,4],
[6,3,5,7,3,5,0,6,5,4,3,4],
[6,5,6,3,4,7,4,0,5,4,5,6],
[7,4,6,5,5,6,5,5,0,6,3,4],
[6,4,7,6,6,6,6,6,4,0,4,5],
[6,2,6,6,5,6,7,5,7,6,0,6],
[7,3,6,5,5,6,6,4,6,5,4,0]])
measure(12,1,rep=1,om=om)

Execution without init...
1961.6967039108276
[[ 1 10 11  8  9  4  6  3  7  2  5  0]
 [ 1 10 11  8  9  4  6  3  7  5  2  0]]
Obtained distance is [270]
[11  0  9  7  5 10  6  8  3  4  1  2]
Execution without borda... (distance = [282])
[11  0  9  7  3 10  8  6  5  2  1  4]
1755.7466118335724
[[ 1 10 11  8  9  4  6  3  7  2  5  0]
 [ 1 10 11  8  9  4  6  3  7  5  2  0]]


array([12, None, 7.0, 48.0, 392.0, 4.833333333333334, 24.166666666666668,
       1961.6967039108276, 1755.7466118335724, 270, 282, '[1 1]'],
      dtype=object)

In [94]:
om = np.array([
[0,6,6,3,3,3,3,3,3,3,0,3],
[4,0,7,7,7,3,4,0,3,4,4,4],
[4,3,0,7,7,3,7,3,3,4,4,7],
[7,3,3,0,3,0,0,0,3,0,0,4],
[7,3,3,7,0,3,4,0,0,4,7,4],
[7,7,7,10,7,0,4,4,3,4,4,4],
[7,6,3,10,6,6,0,3,3,4,3,7],
[7,10,7,10,10,6,7,0,3,4,7,7],
[7,7,7,7,10,7,7,7,0,7,7,7],
[7,6,6,10,6,6,6,6,3,0,3,10],
[10,6,6,10,3,6,7,3,3,7,0,7],
[7,6,3,6,6,6,3,3,3,0,3,0]])
measure(12,1,rep=1,om=om)

Execution without init...
264.78894329071045
[[ 8  7 10  9  2  6 11  5  1  4  3  0]
 [ 8  7 10  9  5  1  2  6 11  4  3  0]
 [ 8  7 10  9  5  2  6 11  1  4  3  0]
 [ 8  7 10  9  6  5  1  2 11  4  3  0]
 [ 8  7 10  9  6 11  5  1  2  4  3  0]]
Obtained distance is [205]
[11  8  4 10  9  7  5  1  0  3  2  6]
Execution without borda... (distance = [219])
[10  7  6 11  9  4  5  1  0  2  3  8]
201.89273190498352
[[ 8  7 10  9  2  6 11  5  1  4  3  0]
 [ 8  7 10  9  5  1  2  6 11  4  3  0]
 [ 8  7 10  9  5  2  6 11  1  4  3  0]
 [ 8  7 10  9  6  5  1  2 11  4  3  0]
 [ 8  7 10  9  6 11  5  1  2  4  3  0]]


array([12, None, 6.0, 66.0, 473.0, 7.5, 48.0, 264.78894329071045,
       201.89273190498352, 205, 219, '[8 8 8 8 8]'], dtype=object)

# n = 8

In [124]:
results8 = np.zeros(0).reshape(0,12)

om = np.array([
[0,3,5,5,4,6,5,3],
[7,0,7,6,7,7,6,5],
[5,3,0,7,6,8,5,5],
[5,4,3,0,5,7,4,6],
[6,3,4,5,0,7,4,6],
[4,3,2,3,3,0,2,4],
[5,4,5,6,6,8,0,5],
[7,5,5,4,4,6,5,0]])

om = np.array([
[0,4,5,7,5,5,4,4],
[6,0,4,6,5,5,4,4],
[5,6,0,7,8,5,4,4],
[3,4,3,0,5,3,3,5],
[5,5,2,5,0,5,4,5],
[5,5,5,7,5,0,4,5],
[6,6,6,7,6,6,0,6],
[6,6,6,5,5,5,4,0]])
results8 = np.vstack((results8, measure(8,1,rep=3,om=om)))

om = np.array([
[0,5,3,4,5,5,4,4],
[5,0,5,5,5,6,5,2],
[7,5,0,7,5,5,8,6],
[6,5,3,0,4,4,6,4],
[5,5,5,6,0,7,6,4],
[5,4,5,6,3,0,7,5],
[6,5,2,4,4,3,0,4],
[6,8,4,6,6,5,6,0]])
results8 = np.vstack((results8, measure(8,1,rep=3,om=om)))

om = np.array([
[0,1,3,3,0,1,0,5],
[9,0,6,5,3,5,5,7],
[7,4,0,2,3,3,3,5],
[7,5,8,0,6,5,4,5],
[10,7,7,4,0,5,5,7],
[9,5,7,5,5,0,4,7],
[10,5,7,6,5,6,0,8],
[5,3,5,5,3,3,2,0]])
results8 = np.vstack((results8, measure(8,1,rep=3,om=om)))

om = np.array([
[0,5,8,4,5,5,5,6],
[5,0,7,4,5,4,8,6],
[2,3,0,2,2,1,4,3],
[6,6,8,0,7,4,6,6],
[5,5,8,3,0,4,6,5],
[5,6,9,6,6,0,6,7],
[5,2,6,4,4,4,0,3],
[4,4,7,4,5,3,7,0]])
results8 = np.vstack((results8, measure(8,1,rep=3,om=om)))

om = np.array([
[0,8,6,6,4,4,6,7],
[2,0,6,5,5,4,4,5],
[4,4,0,7,6,3,4,7],
[4,5,3,0,3,3,4,4],
[6,5,4,7,0,4,6,6],
[6,6,7,7,6,0,8,6],
[4,6,6,6,4,2,0,7],
[3,5,3,6,4,4,3,0]])
results8 = np.vstack((results8, measure(8,1,rep=3,om=om)))

om = np.array([
[0,8,3,4,4,6,3,5],
[2,0,2,2,2,4,3,5],
[7,8,0,6,3,6,4,6],
[6,8,4,0,4,6,1,7],
[6,8,7,6,0,4,4,8],
[4,6,4,4,6,0,3,6],
[7,7,6,9,6,7,0,7],
[5,5,4,3,2,4,3,0]])
results8 = np.vstack((results8, measure(8,1,rep=3,om=om)))

om = np.array([
[0,3,4,4,4,4,3,2],
[7,0,5,6,4,4,5,5],
[6,5,0,4,5,4,4,3],
[6,4,6,0,4,5,5,5],
[6,6,5,6,0,6,5,7],
[6,6,6,5,4,0,6,5],
[7,5,6,5,5,4,0,4],
[8,5,7,5,3,5,6,0]])
results8 = np.vstack((results8, measure(8,1,rep=3,om=om)))

om = np.array([
[0,5,3,5,2,4,6,6],
[5,0,4,4,4,3,3,4],
[7,6,0,6,5,4,6,6],
[5,6,4,0,4,4,6,6],
[8,6,5,6,0,4,5,7],
[6,7,6,6,6,0,7,5],
[4,7,4,4,5,3,0,5],
[4,6,4,4,3,5,5,0]])
results8 = np.vstack((results8, measure(8,1,rep=3,om=om)))

om = np.array([
[0,4,4,6,4,4,3,9],
[6,0,6,5,4,6,5,8],
[6,4,0,6,5,5,3,10],
[4,5,4,0,5,6,4,9],
[6,6,5,5,0,5,3,8],
[6,4,5,4,5,0,4,9],
[7,5,7,6,7,6,0,8],
[1,2,0,1,2,1,2,0]])
results8 = np.vstack((results8, measure(8,1,rep=3,om=om)))

Execution without init...
1.402968406677246
[[6 5 7 2 1 0 3 4]
 [6 5 7 2 1 0 4 3]
 [6 5 7 2 1 4 0 3]
 [6 5 7 2 4 1 0 3]
 [6 7 2 1 0 4 5 3]
 [6 7 2 1 0 5 3 4]
 [6 7 2 1 0 5 4 3]
 [6 7 2 1 4 0 5 3]
 [6 7 2 1 4 5 0 3]
 [6 7 2 1 5 0 3 4]
 [6 7 2 1 5 0 4 3]
 [6 7 2 1 5 4 0 3]
 [6 7 2 4 1 0 5 3]
 [6 7 2 4 1 5 0 3]
 [6 7 2 4 5 1 0 3]
 [6 7 2 5 1 0 3 4]
 [6 7 2 5 1 0 4 3]
 [6 7 2 5 1 4 0 3]
 [6 7 2 5 4 1 0 3]
 [6 7 5 2 1 0 3 4]
 [6 7 5 2 1 0 4 3]
 [6 7 5 2 1 4 0 3]
 [6 7 5 2 4 1 0 3]]
Obtained distance is [117]
[5 4 3 6 7 1 0 2]
Execution with borda... (distance = [121])
[4 5 1 7 6 3 0 2]
1.3078264395395915
[[6 5 7 2 1 0 3 4]
 [6 5 7 2 1 0 4 3]
 [6 5 7 2 1 4 0 3]
 [6 5 7 2 4 1 0 3]
 [6 7 2 1 0 4 5 3]
 [6 7 2 1 0 5 3 4]
 [6 7 2 1 0 5 4 3]
 [6 7 2 1 4 0 5 3]
 [6 7 2 1 4 5 0 3]
 [6 7 2 1 5 0 3 4]
 [6 7 2 1 5 0 4 3]
 [6 7 2 1 5 4 0 3]
 [6 7 2 4 1 0 5 3]
 [6 7 2 4 1 5 0 3]
 [6 7 2 4 5 1 0 3]
 [6 7 2 5 1 0 3 4]
 [6 7 2 5 1 0 4 3]
 [6 7 2 5 1 4 0 3]
 [6 7 2 5 4 1 0 3]
 [6 7 5 2 1 0 3 4]
 [6 7 5 2 1 0

In [125]:
pd.DataFrame(results8).to_csv("results8_kemeny.csv")

In [ ]:
om = np.array([
[0,5,6,3,2,4,6,5,7],
[5,0,6,2,5,4,6,2,4],
[4,4,0,3,5,5,6,2,4],
[7,8,7,0,6,5,8,5,8],
[8,5,5,4,0,5,7,4,7],
[6,6,5,5,5,0,7,4,7],
[4,4,4,2,3,3,0,1,3],
[5,8,8,5,6,6,9,0,6],
[3,6,6,2,3,3,7,4,0]])

om = np.array([
[0,4,8,4,6,6,7,7,6],
[6,0,9,7,6,5,6,6,7],
[2,1,0,4,2,3,2,3,1],
[6,3,6,0,7,7,4,6,3],
[4,4,8,3,0,4,6,5,4],
[4,5,7,3,6,0,6,7,4],
[3,4,8,6,4,4,0,6,4],
[3,4,7,4,5,3,4,0,2],
[4,3,9,7,6,6,6,8,0]])
om = np.array([
[0,6,5,5,3,4,5,8,6],
[4,0,3,4,2,4,3,7,4],
[5,7,0,4,5,7,6,8,6],
[5,6,6,0,5,5,6,9,7],
[7,8,5,5,0,8,7,8,6],
[6,6,3,5,2,0,5,7,5],
[5,7,4,4,3,5,0,7,6],
[2,3,2,1,2,3,3,0,2],
[4,6,4,3,4,5,4,8,0]])
om = np.array([
[0,4,9,4,8,5,4,5,6],
[6,0,6,3,8,5,5,4,5],
[1,4,0,3,7,2,3,4,4],
[6,7,7,0,8,4,6,6,6],
[2,2,3,2,0,1,3,1,3],
[5,5,8,6,9,0,5,6,7],
[6,5,7,4,7,5,0,5,6],
[5,6,6,4,9,4,5,0,7],
[4,5,6,4,7,3,4,3,0]])
om = np.array([
[0,4,5,5,5,5,5,6,4],
[6,0,7,6,6,7,6,8,6],
[5,3,0,5,5,5,3,7,5],
[5,4,5,0,5,5,4,5,5],
[5,4,5,5,0,5,4,7,6],
[5,3,5,5,5,0,6,7,5],
[5,4,7,6,6,4,0,5,4],
[4,2,3,5,3,3,5,0,5],
[6,4,5,5,4,5,6,5,0]])
om = np.array([
[0,5,6,5,7,5,5,3,4],
[5,0,4,4,7,5,6,3,6],
[4,6,0,5,7,7,7,5,5],
[5,6,5,0,7,5,6,5,4],
[3,3,3,3,0,4,5,3,3],
[5,5,3,5,6,0,7,4,6],
[5,4,3,4,5,3,0,3,4],
[7,7,5,5,7,6,7,0,6],
[6,4,5,6,7,4,6,4,0]])
om = np.array([
[0,6,7,3,7,9,6,8,4],
[4,0,4,3,5,7,6,7,3],
[3,6,0,3,4,6,5,6,3],
[7,7,7,0,4,7,5,9,7],
[3,5,6,6,0,7,6,7,6],
[1,3,4,3,3,0,5,6,3],
[4,4,5,5,4,5,0,6,3],
[2,3,4,1,3,4,4,0,4],
[6,7,7,3,4,7,7,6,0]])
om = np.array([
[0,3,3,4,2,7,4,2,2],
[7,0,3,3,6,6,6,4,2],
[7,7,0,4,6,6,5,4,4],
[6,7,6,0,5,6,7,5,6],
[8,4,4,5,0,6,7,3,2],
[3,4,4,4,4,0,5,4,3],
[6,4,5,3,3,5,0,3,1],
[8,6,6,5,7,6,7,0,5],
[8,8,6,4,8,7,9,5,0]])
om = np.array([
[0,7,3,3,6,7,5,4,2],
[3,0,3,4,3,5,4,4,2],
[7,7,0,5,6,8,6,6,3],
[7,6,5,0,5,5,5,6,4],
[4,7,4,5,0,8,6,7,4],
[3,5,2,5,2,0,2,4,3],
[5,6,4,5,4,8,0,5,3],
[6,6,4,4,3,6,5,0,2],
[8,8,7,6,6,7,7,8,0]])


In [112]:
results8

array([[12, None, 4.0, 18.0, 166.0, 5.0, 18.5, 1.0581266085306804,
        0.9435755411783854, 114, 118, '[2 2]'],
       [12, None, 5.0, 19.0, 186.0, 3.833333333333333,
        14.833333333333332, 0.6430047353108724, 0.4289969603220622, 94,
        96, '[6 6 6 6 6 6 6 6 6 6 6 6]'],
       [12, None, 5.0, 22.0, 178.0, 3.8333333333333335, 11.5,
        0.574927806854248, 0.5179723898569742, 102, 102,
        '[5. 5. 5. 5. 5. 5. 5. 5.]'],
       [12, None, 5.0, 25.0, 176.0, 5.0, 22.5, 0.6839884122212728,
        0.6610490481058756, 106, 112, '[5]'],
       [12, None, 4.0, 26.0, 186.0, 5.0, 23.5, 0.5642766952514648,
        0.3554356098175049, 96, 96, '[6. 6.]']], dtype=object)

# n = 9

In [129]:
results9 = np.zeros(0).reshape(0,12)

print('## 1#########################')
om = np.array([
[0,6,6,5,6,4,4,5,3],
[4,0,2,3,3,3,4,4,2],
[4,8,0,6,6,4,5,6,5],
[5,7,4,0,4,5,5,6,3],
[4,7,4,6,0,6,5,8,5],
[6,7,6,5,4,0,6,7,4],
[6,6,5,5,5,4,0,5,4],
[5,6,4,4,2,3,5,0,3],
[7,8,5,7,5,6,6,7,0]])
results9 = np.vstack((results9, measure(9,0,rep=1,om=om)))
print('## 2#########################')
om = np.array([
[0,7,5,7,5,5,4,7,5],
[3,0,4,4,4,3,4,5,3],
[5,6,0,5,4,5,6,8,5],
[3,6,5,0,4,4,4,7,5],
[5,6,6,6,0,5,6,7,4],
[5,7,5,6,5,0,7,6,5],
[6,6,4,6,4,3,0,6,3],
[3,5,2,3,3,4,4,0,2],
[5,7,5,5,6,5,7,8,0]])
results9 = np.vstack((results9, measure(9,0,rep=1,om=om)))
print('## 3#########################')
om = np.array([
[0,3,4,2,3,3,3,1,3],
[7,0,6,4,5,2,4,5,5],
[6,4,0,3,5,3,6,4,5],
[8,6,7,0,8,3,7,6,5],
[7,5,5,2,0,3,4,4,5],
[7,8,7,7,7,0,7,6,7],
[7,6,4,3,6,3,0,4,5],
[9,5,6,4,6,4,6,0,6],
[7,5,5,5,5,3,5,4,0]])
results9 = np.vstack((results9, measure(9,0,rep=1,om=om)))
print('## 4#########################')
om = np.array([
[0,4,4,3,5,5,3,3,5],
[6,0,5,5,4,6,4,2,4],
[6,5,0,6,7,7,5,3,7],
[7,5,4,0,7,4,5,5,7],
[5,6,3,3,0,5,4,1,7],
[5,4,3,6,5,0,4,5,5],
[7,6,5,5,6,6,0,3,8],
[7,8,7,5,9,5,7,0,8],
[5,6,3,3,3,5,2,2,0]])
results9 = np.vstack((results9, measure(9,0,rep=1,om=om)))
print('## 5#########################')
om = np.array([
[0,5,6,3,5,3,5,7,6],
[5,0,7,5,6,5,5,7,7],
[4,3,0,3,7,4,5,7,3],
[7,5,7,0,8,6,6,7,7],
[5,4,3,2,0,3,5,6,4],
[7,5,6,4,7,0,5,7,6],
[5,5,5,4,5,5,0,8,6],
[3,3,3,3,4,3,2,0,4],
[4,3,7,3,6,4,4,6,0]])
results9 = np.vstack((results9, measure(9,0,rep=1,om=om)))
print('## 6#########################')
om = np.array([
[0,5,5,5,5,5,7,5,4],
[5,0,2,5,4,5,2,2,6],
[5,8,0,7,6,6,7,6,7],
[5,5,3,0,6,4,5,6,6],
[5,6,4,4,0,4,6,6,5],
[5,5,4,6,6,0,7,6,6],
[3,8,3,5,4,3,0,5,5],
[5,8,4,4,4,4,5,0,7],
[6,4,3,4,5,4,5,3,0]])
results9 = np.vstack((results9, measure(9,0,rep=1,om=om)))
print('## 7#########################')
om = np.array([
[0,5,3,3,6,6,4,2,5],
[5,0,5,3,5,4,0,4,5],
[7,5,0,5,5,7,3,4,4],
[7,7,5,0,6,6,6,4,4],
[4,5,5,4,0,6,3,4,6],
[4,6,3,4,4,0,3,2,4],
[6,10,7,4,7,7,0,5,6],
[8,6,6,6,6,8,5,0,5],
[5,5,6,6,4,6,4,5,0]])
results9 = np.vstack((results9, measure(9,0,rep=1,om=om)))
print('## 8#########################')
om = np.array([
[0,3,4,5,6,7,8,6,6],
[7,0,8,6,5,7,7,5,7],
[6,2,0,4,6,7,7,7,6],
[5,4,6,0,6,8,7,5,6],
[4,5,4,4,0,6,6,5,6],
[3,3,3,2,4,0,6,5,5],
[2,3,3,3,4,4,0,4,3],
[4,5,3,5,5,5,6,0,5],
[4,3,4,4,4,5,7,5,0]])
results9 = np.vstack((results9, measure(9,0,rep=1,om=om)))
print('## 9#########################')
om = np.array([
[0,7,5,6,3,6,6,5,5],
[3,0,6,6,3,8,4,3,8],
[5,4,0,5,4,5,5,4,6],
[4,4,5,0,4,7,6,6,5],
[7,7,6,6,0,7,6,4,7],
[4,2,5,3,3,0,4,1,4],
[4,6,5,4,4,6,0,5,6],
[5,7,6,4,6,9,5,0,8],
[5,2,4,5,3,6,4,2,0]])
results9 = np.vstack((results9, measure(9,0,rep=1,om=om)))
print('## 10#########################')
om = np.array([
[0,7,8,6,4,5,5,5,6],
[3,0,6,2,2,5,4,4,2],
[2,4,0,2,1,3,3,1,1],
[4,8,8,0,3,6,7,5,3],
[6,8,9,7,0,8,6,7,6],
[5,5,7,4,2,0,3,5,5],
[5,6,7,3,4,7,0,5,4],
[5,6,9,5,3,5,5,0,6],
[4,8,9,7,4,5,6,4,0]])
results9 = np.vstack((results9, measure(9,0,rep=1,om=om)))
print('## 11#########################')
om = np.array([
[0,7,9,4,6,8,8,7,7],
[3,0,4,3,5,5,4,5,4],
[1,6,0,3,5,6,7,5,5],
[6,7,7,0,4,7,5,6,6],
[4,5,5,6,0,8,8,7,7],
[2,5,4,3,2,0,6,4,5],
[2,6,3,5,2,4,0,6,6],
[3,5,5,4,3,6,4,0,4],
[3,6,5,4,3,5,4,6,0]])
results9 = np.vstack((results9, measure(9,0,rep=1,om=om)))
print('## 12#########################')
om = np.array([
[0,5,3,4,3,4,5,5,5],
[5,0,4,4,5,5,5,3,6],
[7,6,0,7,6,7,5,4,7],
[6,6,3,0,7,6,5,5,7],
[7,5,4,3,0,5,4,5,6],
[6,5,3,4,5,0,4,5,7],
[5,5,5,5,6,6,0,5,6],
[5,7,6,5,5,5,5,0,7],
[5,4,3,3,4,3,4,3,0]])
results9 = np.vstack((results9, measure(9,0,rep=1,om=om)))
print('## 13#########################')
om = np.array([
[0,4,3,4,6,4,5,4,4],
[6,0,3,6,5,5,5,5,4],
[7,7,0,7,8,7,6,7,6],
[6,4,3,0,6,5,6,7,4],
[4,5,2,4,0,4,7,4,3],
[6,5,3,5,6,0,5,5,3],
[5,5,4,4,3,5,0,3,3],
[6,5,3,3,6,5,7,0,4],
[6,6,4,6,7,7,7,6,0]])
results9 = np.vstack((results9, measure(9,0,rep=1,om=om)))
print('## 14#########################')
om = np.array([
[0,3,6,6,7,7,4,3,6],
[7,0,7,7,7,8,7,5,8],
[4,3,0,6,6,8,5,3,4],
[4,3,4,0,4,6,4,2,5],
[3,3,4,6,0,8,5,2,4],
[3,2,2,4,2,0,2,3,3],
[6,3,5,6,5,8,0,3,6],
[7,5,7,8,8,7,7,0,8],
[4,2,6,5,6,7,4,2,0]])
results9 = np.vstack((results9, measure(9,0,rep=1,om=om)))
print('## 15#########################')
om = np.array([
[0,2,5,4,4,4,4,5,3],
[8,0,4,4,6,4,4,6,5],
[5,6,0,6,6,7,5,6,5],
[6,6,4,0,5,4,3,6,4],
[6,4,4,5,0,4,2,7,3],
[6,6,3,6,6,0,3,8,2],
[6,6,5,7,8,7,0,9,4],
[5,4,4,4,3,2,1,0,2],
[7,5,5,6,7,8,6,8,0]])
results9 = np.vstack((results9, measure(9,0,rep=1,om=om)))
print('## 16#########################')
om = np.array([
[0,5,6,7,7,9,5,8,5],
[5,0,3,5,5,7,6,6,5],
[4,7,0,6,6,8,5,7,4],
[3,5,4,0,6,7,4,6,4],
[3,5,4,4,0,4,3,7,3],
[1,3,2,3,6,0,3,5,4],
[5,4,5,6,7,7,0,6,3],
[2,4,3,4,3,5,4,0,3],
[5,5,6,6,7,6,7,7,0]])
results9 = np.vstack((results9, measure(9,0,rep=1,om=om)))
print('## 17#########################')
om = np.array([
[0,5,7,6,7,5,3,9,5],
[5,0,7,6,6,4,5,8,7],
[3,3,0,5,6,3,2,6,3],
[4,4,5,0,5,5,5,9,5],
[3,4,4,5,0,5,2,8,5],
[5,6,7,5,5,0,3,7,5],
[7,5,8,5,8,7,0,7,5],
[1,2,4,1,2,3,3,0,4],
[5,3,7,5,5,5,5,6,0]])
results9 = np.vstack((results9, measure(9,0,rep=1,om=om)))
print('## 18#########################')
om = np.array([
[0,6,6,7,6,7,7,8,7],
[4,0,7,7,4,5,7,7,6],
[4,3,0,6,4,3,7,8,6],
[3,3,4,0,3,3,7,7,3],
[4,6,6,7,0,5,5,7,6],
[3,5,7,7,5,0,7,8,4],
[3,3,3,3,5,3,0,5,4],
[2,3,2,3,3,2,5,0,5],
[3,4,4,7,4,6,6,5,0]])
results9 = np.vstack((results9, measure(9,0,rep=1,om=om)))
print('## 19#########################')
om = np.array([
[0,4,5,6,7,6,5,6,8],
[6,0,7,5,7,6,7,7,8],
[5,3,0,6,6,5,4,7,8],
[4,5,4,0,6,6,5,5,7],
[3,3,4,4,0,5,2,4,5],
[4,4,5,4,5,0,5,7,7],
[5,3,6,5,8,5,0,9,7],
[4,3,3,5,6,3,1,0,5],
[2,2,2,3,5,3,3,5,0]])
results9 = np.vstack((results9, measure(9,0,rep=1,om=om)))
print('## 20#########################')
om = np.array([
[0,5,7,4,4,5,8,7,5],
[5,0,7,5,5,6,4,6,7],
[3,3,0,3,2,4,4,3,4],
[6,5,7,0,6,5,7,7,7],
[6,5,8,4,0,6,7,6,7],
[5,4,6,5,4,0,4,4,5],
[2,6,6,3,3,6,0,5,4],
[3,4,7,3,4,6,5,0,4],
[5,3,6,3,3,5,6,6,0]])
results9 = np.vstack((results9, measure(9,0,rep=1,om=om)))

## 1#########################
Execution without init...
6.059638023376465
[[8 5 6 0 2 4 3 7 1]]
Obtained distance is [142]
[3 8 4 6 5 1 2 7 0]
Execution with borda... (distance = [146])
[5 8 3 6 1 2 4 7 0]
5.530539035797119
[[8 5 6 0 2 4 3 7 1]]
## 2#########################
Execution without init...
5.054440975189209
[[5 8 4 2 6 0 3 1 7]
 [5 8 4 2 6 0 3 7 1]
 [8 4 2 5 6 0 3 1 7]
 [8 4 2 5 6 0 3 7 1]
 [8 4 5 2 6 0 3 1 7]
 [8 4 5 2 6 0 3 7 1]
 [8 5 4 2 6 0 3 1 7]
 [8 5 4 2 6 0 3 7 1]]
Obtained distance is [142]
[5 7 3 6 2 0 4 8 1]
Execution with borda... (distance = [146])
[2 7 4 5 3 1 6 8 0]
4.92225980758667
[[5 8 4 2 6 0 3 1 7]
 [5 8 4 2 6 0 3 7 1]
 [8 4 2 5 6 0 3 1 7]
 [8 4 2 5 6 0 3 7 1]
 [8 4 5 2 6 0 3 1 7]
 [8 4 5 2 6 0 3 7 1]
 [8 5 4 2 6 0 3 1 7]
 [8 5 4 2 6 0 3 7 1]]
## 3#########################
Execution without init...
4.983818769454956
[[5 3 1 7 2 6 4 8 0]
 [5 3 1 7 2 6 8 4 0]
 [5 3 1 7 2 8 6 4 0]
 [5 3 1 7 8 2 6 4 0]
 [5 3 7 1 2 6 4 8 0]
 [5 3 7 1 2 6 8 4 0]
 [5 3 7 1 2 8 6

6.765047073364258
[[6 7 2 3 1 4 5 0 8]
 [6 7 2 3 1 4 5 8 0]
 [6 7 2 3 1 5 4 0 8]
 [6 7 2 3 1 5 4 8 0]
 [6 7 2 3 4 1 5 0 8]
 [6 7 2 3 4 1 5 8 0]
 [6 7 2 3 4 5 0 1 8]
 [6 7 2 3 4 5 1 0 8]
 [6 7 2 3 4 5 1 8 0]
 [6 7 2 3 5 1 4 0 8]
 [6 7 2 3 5 1 4 8 0]
 [6 7 2 3 5 4 0 1 8]
 [6 7 2 3 5 4 1 0 8]
 [6 7 2 3 5 4 1 8 0]
 [7 2 3 1 6 4 5 0 8]
 [7 2 3 1 6 4 5 8 0]
 [7 2 3 1 6 5 4 0 8]
 [7 2 3 1 6 5 4 8 0]
 [7 2 3 6 1 4 5 0 8]
 [7 2 3 6 1 4 5 8 0]
 [7 2 3 6 1 5 4 0 8]
 [7 2 3 6 1 5 4 8 0]
 [7 2 3 6 4 1 5 0 8]
 [7 2 3 6 4 1 5 8 0]
 [7 2 3 6 4 5 0 1 8]
 [7 2 3 6 4 5 1 0 8]
 [7 2 3 6 4 5 1 8 0]
 [7 2 3 6 5 1 4 0 8]
 [7 2 3 6 5 1 4 8 0]
 [7 2 3 6 5 4 0 1 8]
 [7 2 3 6 5 4 1 0 8]
 [7 2 3 6 5 4 1 8 0]
 [7 2 6 3 1 4 5 0 8]
 [7 2 6 3 1 4 5 8 0]
 [7 2 6 3 1 5 4 0 8]
 [7 2 6 3 1 5 4 8 0]
 [7 2 6 3 4 1 5 0 8]
 [7 2 6 3 4 1 5 8 0]
 [7 2 6 3 4 5 0 1 8]
 [7 2 6 3 4 5 1 0 8]
 [7 2 6 3 4 5 1 8 0]
 [7 2 6 3 5 1 4 0 8]
 [7 2 6 3 5 1 4 8 0]
 [7 2 6 3 5 4 0 1 8]
 [7 2 6 3 5 4 1 0 8]
 [7 2 6 3 5 4 1 8 0]
 [7 6 2 3 1 4 5 

In [130]:
pd.DataFrame(results9).to_csv("results9_kemeny.csv")

# n = 10

In [135]:
results10 = np.zeros(0).reshape(0,12)

om = np.array([
[0,3,3,4,3,2,3,4,2,3],
[7,0,4,6,4,5,5,4,4,6],
[7,6,0,6,7,6,3,7,4,4],
[6,4,4,0,3,3,4,5,4,3],
[7,6,3,7,0,4,5,6,4,5],
[8,5,4,7,6,0,5,5,5,5],
[7,5,7,6,5,5,0,5,6,4],
[6,6,3,5,4,5,5,0,4,6],
[8,6,6,6,6,5,4,6,0,4],
[7,4,6,7,5,5,6,4,6,0]])
results10 = np.vstack((results10, measure(10,0,rep=1,om=om)))
print('## 5#########################')
om = np.array([
[0,7,7,7,6,8,6,8,7,7],
[3,0,5,6,5,4,4,5,4,6],
[3,5,0,7,3,4,3,6,5,5],
[3,4,3,0,2,4,3,6,5,5],
[4,5,7,8,0,6,5,7,7,6],
[2,6,6,6,4,0,5,6,4,4],
[4,6,7,7,5,5,0,7,5,6],
[2,5,4,4,3,4,3,0,2,5],
[3,6,5,5,3,6,5,8,0,5],
[3,4,5,5,4,6,4,5,5,0]])
results10 = np.vstack((results10, measure(10,0,rep=1,om=om)))
print('## 6#########################')
om = np.array([
[0,5,4,5,4,6,2,8,4,4],
[5,0,4,5,3,5,3,5,4,5],
[6,6,0,6,4,6,3,10,6,2],
[5,5,4,0,1,3,3,6,6,5],
[6,7,6,9,0,5,6,8,7,5],
[4,5,4,7,5,0,4,7,5,4],
[8,7,7,7,4,6,0,8,7,7],
[2,5,0,4,2,3,2,0,3,2],
[6,6,4,4,3,5,3,7,0,5],
[6,5,8,5,5,6,3,8,5,0]])
results10 = np.vstack((results10, measure(10,0,rep=1,om=om)))
print('## 7#########################')
om = np.array([
[0,5,5,6,3,5,6,5,5,5],
[5,0,6,5,3,5,8,6,6,4],
[5,4,0,4,4,4,5,5,4,4],
[4,5,6,0,5,4,5,5,5,4],
[7,7,6,5,0,7,5,6,6,7],
[5,5,6,6,3,0,6,7,6,5],
[4,2,5,5,5,4,0,4,3,4],
[5,4,5,5,4,3,6,0,5,4],
[5,4,6,5,4,4,7,5,0,4],
[5,6,6,6,3,5,6,6,6,0]])
results10 = np.vstack((results10, measure(10,0,rep=1,om=om)))
print('## 8#########################')
om = np.array([
[0,6,3,5,7,6,8,5,5,8],
[4,0,2,4,6,6,8,3,5,6],
[7,8,0,8,7,9,8,5,7,7],
[5,6,2,0,6,8,8,5,4,7],
[3,4,3,4,0,6,6,4,6,5],
[4,4,1,2,4,0,6,2,3,4],
[2,2,2,2,4,4,0,0,3,1],
[5,7,5,5,6,8,10,0,7,6],
[5,5,3,6,4,7,7,3,0,5],
[2,4,3,3,5,6,9,4,5,0]])
results10 = np.vstack((results10, measure(10,0,rep=1,om=om)))
print('## 9#########################')
om = np.array([
[0,5,7,4,5,5,7,4,3,4],
[5,0,5,4,4,5,8,5,2,5],
[3,5,0,3,4,3,6,6,1,2],
[6,6,7,0,6,5,6,5,3,5],
[5,6,6,4,0,5,6,5,1,4],
[5,5,7,5,5,0,5,5,4,3],
[3,2,4,4,4,5,0,2,3,3],
[6,5,4,5,5,5,8,0,3,5],
[7,8,9,7,9,6,7,7,0,5],
[6,5,8,5,6,7,7,5,5,0]])
results10 = np.vstack((results10, measure(10,0,rep=1,om=om)))
print('## 10#########################')
om = np.array([
[0,6,2,5,2,4,2,4,5,3],
[4,0,3,5,4,7,5,5,5,4],
[8,7,0,6,6,7,6,7,7,8],
[5,5,4,0,4,7,2,6,6,5],
[8,6,4,6,0,7,5,6,5,8],
[6,3,3,3,3,0,2,4,6,5],
[8,5,4,8,5,8,0,7,6,7],
[6,5,3,4,4,6,3,0,5,5],
[5,5,3,4,5,4,4,5,0,5],
[7,6,2,5,2,5,3,5,5,0]])
results10 = np.vstack((results10, measure(10,0,rep=1,om=om)))
print('## 1#########################')
om = np.array([
[0,6,4,7,6,5,5,7,4,8],
[4,0,6,7,5,4,7,7,5,5],
[6,4,0,8,6,6,7,6,5,5],
[3,3,2,0,1,5,6,5,2,4],
[4,5,4,9,0,5,6,6,3,6],
[5,6,4,5,5,0,7,6,4,6],
[5,3,3,4,4,3,0,5,3,4],
[3,3,4,5,4,4,5,0,3,4],
[6,5,5,8,7,6,7,7,0,6],
[2,5,5,6,4,4,6,6,4,0]])
results10 = np.vstack((results10, measure(10,0,rep=1,om=om)))
print('## 2#########################')
om = np.array([
[0,5,6,5,7,5,5,8,4,5],
[5,0,4,6,6,2,5,5,4,4],
[4,6,0,6,6,3,5,6,4,5],
[5,4,4,0,4,2,4,5,5,5],
[3,4,4,6,0,3,5,4,3,5],
[5,8,7,8,7,0,5,7,5,6],
[5,5,5,6,5,5,0,8,6,6],
[2,5,4,5,6,3,2,0,1,3],
[6,6,6,5,7,5,4,9,0,6],
[5,6,5,5,5,4,4,7,4,0]])
results10 = np.vstack((results10, measure(10,0,rep=1,om=om)))
print('## 3#########################')
om = np.array([
[0,3,5,5,4,6,6,5,6,3],
[7,0,4,5,6,8,7,8,7,2],
[5,6,0,7,3,8,6,7,6,3],
[5,5,3,0,5,8,7,7,6,3],
[6,4,7,5,0,7,6,6,6,2],
[4,2,2,2,3,0,4,3,3,1],
[4,3,4,3,4,6,0,5,5,2],
[5,2,3,3,4,7,5,0,5,0],
[4,3,4,4,4,7,5,5,0,3],
[7,8,7,7,8,9,8,10,7,0]])
results10 = np.vstack((results10, measure(10,0,rep=1,om=om)))

Execution without init...
48.71708106994629
[[9 6 8 2 5 4 7 1 3 0]]
Obtained distance is [179]
[9 7 3 8 5 4 1 6 2 0]
Execution with borda... (distance = [193])
[9 6 1 8 5 2 3 7 0 4]
39.624109745025635
[[9 6 8 2 5 4 7 1 3 0]]
## 5#########################
Execution without init...
25.387495040893555
[[0 4 6 8 1 9 5 2 3 7]
 [0 4 6 8 5 1 2 3 7 9]
 [0 4 6 8 5 1 2 3 9 7]
 [0 4 6 8 5 1 2 9 3 7]
 [0 4 6 8 5 1 9 2 3 7]
 [0 4 6 8 5 2 1 3 7 9]
 [0 4 6 8 5 2 1 3 9 7]
 [0 4 6 8 5 2 1 9 3 7]
 [0 4 6 8 9 5 1 2 3 7]
 [0 4 6 8 9 5 2 1 3 7]
 [0 4 6 9 8 5 1 2 3 7]
 [0 4 6 9 8 5 2 1 3 7]
 [0 4 8 5 6 1 2 3 7 9]
 [0 4 8 5 6 1 2 3 9 7]
 [0 4 8 5 6 1 2 9 3 7]
 [0 4 8 5 6 1 9 2 3 7]
 [0 4 8 5 6 2 1 3 7 9]
 [0 4 8 5 6 2 1 3 9 7]
 [0 4 8 5 6 2 1 9 3 7]
 [0 4 8 6 1 9 5 2 3 7]
 [0 4 8 6 5 1 2 3 7 9]
 [0 4 8 6 5 1 2 3 9 7]
 [0 4 8 6 5 1 2 9 3 7]
 [0 4 8 6 5 1 9 2 3 7]
 [0 4 8 6 5 2 1 3 7 9]
 [0 4 8 6 5 2 1 3 9 7]
 [0 4 8 6 5 2 1 9 3 7]
 [0 4 8 6 9 5 1 2 3 7]
 [0 4 8 6 9 5 2 1 3 7]
 [0 6 4 8 1 9 5 2 3 7]
 [0 6 4 8 

25.644597053527832
[[2 8 0 4 5 1 9 3 6 7]
 [2 8 0 4 5 1 9 3 7 6]
 [2 8 0 4 5 1 9 7 3 6]
 [2 8 0 4 5 9 1 3 6 7]
 [2 8 0 4 5 9 1 3 7 6]
 [2 8 0 4 5 9 1 7 3 6]
 [2 8 0 5 1 4 9 3 6 7]
 [2 8 0 5 1 4 9 3 7 6]
 [2 8 0 5 1 4 9 7 3 6]
 [2 8 0 5 4 1 9 3 6 7]
 [2 8 0 5 4 1 9 3 7 6]
 [2 8 0 5 4 1 9 7 3 6]
 [2 8 0 5 4 9 1 3 6 7]
 [2 8 0 5 4 9 1 3 7 6]
 [2 8 0 5 4 9 1 7 3 6]
 [2 8 5 0 1 4 9 3 6 7]
 [2 8 5 0 1 4 9 3 7 6]
 [2 8 5 0 1 4 9 7 3 6]
 [2 8 5 0 4 1 9 3 6 7]
 [2 8 5 0 4 1 9 3 7 6]
 [2 8 5 0 4 1 9 7 3 6]
 [2 8 5 0 4 9 1 3 6 7]
 [2 8 5 0 4 9 1 3 7 6]
 [2 8 5 0 4 9 1 7 3 6]
 [8 2 0 4 5 1 9 3 6 7]
 [8 2 0 4 5 1 9 3 7 6]
 [8 2 0 4 5 1 9 7 3 6]
 [8 2 0 4 5 9 1 3 6 7]
 [8 2 0 4 5 9 1 3 7 6]
 [8 2 0 4 5 9 1 7 3 6]
 [8 2 0 5 1 4 9 3 6 7]
 [8 2 0 5 1 4 9 3 7 6]
 [8 2 0 5 1 4 9 7 3 6]
 [8 2 0 5 4 1 9 3 6 7]
 [8 2 0 5 4 1 9 3 7 6]
 [8 2 0 5 4 1 9 7 3 6]
 [8 2 0 5 4 9 1 3 6 7]
 [8 2 0 5 4 9 1 3 7 6]
 [8 2 0 5 4 9 1 7 3 6]
 [8 2 5 0 1 4 9 3 6 7]
 [8 2 5 0 1 4 9 3 7 6]
 [8 2 5 0 1 4 9 7 3 6]
 [8 2 5 0 4 1 9

In [136]:
pd.DataFrame(results10).to_csv("results10_kemeny.csv")

In [137]:
results10

array([[10, None, 7.0, 35.0, 275.0, 4.333333333333334,
        16.333333333333332, 48.71708106994629, 39.624109745025635, 179,
        193, '[9]'],
       [10, None, 4.0, 33.0, 278.0, 7.0, 35.5, 25.387495040893555,
        25.1004159450531, 174, 174,
        '[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.\n 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]'],
       [10, None, 5.0, 34.0, 288.0, 5.833333333333333, 34.5,
        23.706909894943237, 17.722270965576172, 164, 168,
        '[4 4 4 4 4 4 4 4 4 4]'],
       [10, None, 5.0, 28.0, 261.0, 5.5, 29.0, 54.758546113967896,
        48.29395031929016, 189, 189,
        '[4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.\n 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.\n 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.\n 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.\n 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.

# n = 10

In [139]:
results11 = np.zeros(0).reshape(0,12)
print('## 1 ########################')
om = np.array([
[0,3,5,6,5,5,6,6,4,4],
[7,0,6,8,6,7,6,9,6,2],
[5,4,0,6,6,4,6,9,7,5],
[4,2,4,0,4,5,5,7,5,3],
[5,4,4,6,0,6,4,8,7,2],
[5,3,6,5,4,0,5,7,6,3],
[4,4,4,5,6,5,0,8,5,3],
[4,1,1,3,2,3,2,0,3,1],
[6,4,3,5,3,4,5,7,0,3],
[6,8,5,7,8,7,7,9,7,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))
print('## 2 ########################')
om = np.array([
[0,3,6,5,5,7,5,5,6,7],
[7,0,7,6,9,7,7,7,8,9],
[4,3,0,6,5,6,5,5,7,3],
[5,4,4,0,5,5,5,4,5,6],
[5,1,5,5,0,5,5,7,6,6],
[3,3,4,5,5,0,3,5,6,5],
[5,3,5,5,5,7,0,5,6,5],
[5,3,5,6,3,5,5,0,4,6],
[4,2,3,5,4,4,4,6,0,4],
[3,1,7,4,4,5,5,4,6,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))
print('## 3 ########################')
om = np.array([
[0,4,8,7,5,4,4,7,8,7],
[6,0,6,5,4,7,5,6,9,8],
[2,4,0,5,4,4,3,5,6,4],
[3,5,5,0,4,4,4,6,6,4],
[5,6,6,6,0,6,6,7,8,5],
[6,3,6,6,4,0,5,7,8,6],
[6,5,7,6,4,5,0,6,8,6],
[3,4,5,4,3,3,4,0,5,4],
[2,1,4,4,2,2,2,5,0,4],
[3,2,6,6,5,4,4,6,6,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))
print('## 4 ########################')
om = np.array([
[0,5,6,5,5,6,2,4,7,6],
[5,0,7,6,7,7,5,5,8,6],
[4,3,0,4,4,6,2,3,5,4],
[5,4,6,0,4,6,4,2,6,5],
[5,3,6,6,0,8,3,3,7,4],
[4,3,4,4,2,0,2,3,4,3],
[8,5,8,6,7,8,0,4,5,6],
[6,5,7,8,7,7,6,0,8,5],
[3,2,5,4,3,6,5,2,0,5],
[4,4,6,5,6,7,4,5,5,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))
print('## 5 ########################')
om = np.array([
[0,4,6,4,6,5,4,5,6,5],
[6,0,5,4,5,4,4,6,4,7],
[4,5,0,4,4,6,5,3,6,7],
[6,6,6,0,6,5,4,4,4,8],
[4,5,6,4,0,6,3,5,5,6],
[5,6,4,5,4,0,4,5,5,8],
[6,6,5,6,7,6,0,5,4,8],
[5,4,7,6,5,5,5,0,5,7],
[4,6,4,6,5,5,6,5,0,6],
[5,3,3,2,4,2,2,3,4,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))
print('## 6 ########################')
om = np.array([
[0,2,4,4,5,3,2,3,1,1],
[8,0,7,7,8,6,4,7,7,5],
[6,3,0,4,4,4,4,4,3,0],
[6,3,6,0,6,7,5,6,5,3],
[5,2,6,4,0,3,3,3,1,2],
[7,4,6,3,7,0,3,5,5,3],
[8,6,6,5,7,7,0,7,6,3],
[7,3,6,4,7,5,3,0,5,4],
[9,3,7,5,9,5,4,5,0,4],
[9,5,10,7,8,7,7,6,6,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))
print('## 7 ########################')
om = np.array([
[0,6,6,6,6,6,6,5,7,6],
[4,0,3,3,3,4,4,3,5,4],
[4,7,0,6,4,5,6,6,6,6],
[4,7,4,0,4,5,7,7,4,6],
[4,7,6,6,0,7,7,6,7,8],
[4,6,5,5,3,0,5,5,6,7],
[4,6,4,3,3,5,0,5,6,7],
[5,7,4,3,4,5,5,0,6,5],
[3,5,4,6,3,4,4,4,0,5],
[4,6,4,4,2,3,3,5,5,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))
print('## 8 ########################')
om = np.array([
[0,3,6,4,6,4,4,5,6,5],
[7,0,6,7,6,7,7,8,7,6],
[4,4,0,3,3,6,3,6,3,3],
[6,3,7,0,4,7,6,7,7,6],
[4,4,7,6,0,6,5,6,6,5],
[6,3,4,3,4,0,6,5,4,5],
[6,3,7,4,5,4,0,5,5,6],
[5,2,4,3,4,5,5,0,4,4],
[4,3,7,3,4,6,5,6,0,5],
[5,4,7,4,5,5,4,6,5,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))
print('## 9 ########################')
om = np.array([
[0,4,6,4,6,7,6,5,5,7],
[6,0,6,4,5,6,6,5,5,5],
[4,4,0,3,5,4,4,5,4,3],
[6,6,7,0,6,6,6,7,6,7],
[4,5,5,4,0,3,3,5,4,5],
[3,4,6,4,7,0,5,5,5,6],
[4,4,6,4,7,5,0,6,5,6],
[5,5,5,3,5,5,4,0,4,5],
[5,5,6,4,6,5,5,6,0,6],
[3,5,7,3,5,4,4,5,4,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))
print('## 10 ########################')
om = np.array([
[0,5,8,5,6,7,6,6,4,7],
[5,0,7,7,6,5,4,3,4,5],
[2,3,0,4,4,6,3,3,3,6],
[5,3,6,0,6,3,7,4,5,6],
[4,4,6,4,0,5,5,4,3,7],
[3,5,4,7,5,0,4,5,4,4],
[4,6,7,3,5,6,0,4,4,5],
[4,7,7,6,6,5,6,0,5,5],
[6,6,7,5,7,6,6,5,0,6],
[3,5,4,4,3,6,5,5,4,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))

## 1 ########################
Execution without init...
19.669431924819946
[[9 1 0 2 6 4 3 5 8 7]
 [9 1 0 2 6 4 5 3 8 7]
 [9 1 0 2 6 4 5 8 3 7]
 [9 1 0 5 2 6 4 3 8 7]
 [9 1 0 5 2 6 4 8 3 7]
 [9 1 2 0 6 4 3 5 8 7]
 [9 1 2 0 6 4 5 3 8 7]
 [9 1 2 0 6 4 5 8 3 7]
 [9 1 2 4 5 8 0 3 6 7]
 [9 1 2 4 5 8 0 6 3 7]
 [9 1 2 6 4 5 8 0 3 7]
 [9 1 4 5 2 8 0 3 6 7]
 [9 1 4 5 2 8 0 6 3 7]
 [9 1 5 0 2 6 4 3 8 7]
 [9 1 5 0 2 6 4 8 3 7]
 [9 1 5 2 0 6 4 3 8 7]
 [9 1 5 2 0 6 4 8 3 7]
 [9 1 5 2 4 8 0 3 6 7]
 [9 1 5 2 4 8 0 6 3 7]
 [9 1 5 2 6 4 8 0 3 7]]
Obtained distance is [163]
[2 1 3 6 5 7 4 9 8 0]
Execution with borda... (distance = [165])
[4 1 2 8 3 5 6 9 7 0]
17.753665924072266
[[9 1 0 2 6 4 3 5 8 7]
 [9 1 0 2 6 4 5 3 8 7]
 [9 1 0 2 6 4 5 8 3 7]
 [9 1 0 5 2 6 4 3 8 7]
 [9 1 0 5 2 6 4 8 3 7]
 [9 1 2 0 6 4 3 5 8 7]
 [9 1 2 0 6 4 5 3 8 7]
 [9 1 2 0 6 4 5 8 3 7]
 [9 1 2 4 5 8 0 3 6 7]
 [9 1 2 4 5 8 0 6 3 7]
 [9 1 2 6 4 5 8 0 3 7]
 [9 1 4 5 2 8 0 3 6 7]
 [9 1 4 5 2 8 0 6 3 7]
 [9 1 5 0 2 6 4 3 8 7]
 [9 1 5 0

9.623703956604004
[[9 6 1 3 5 7 8 4 2 0]
 [9 6 1 3 5 8 7 4 2 0]
 [9 6 1 3 7 5 8 4 2 0]
 [9 6 1 3 7 8 5 4 2 0]
 [9 6 1 3 8 5 7 4 2 0]
 [9 6 1 3 8 7 5 4 2 0]
 [9 6 1 8 3 5 7 4 2 0]
 [9 6 1 8 3 7 5 4 2 0]]
## 7 ########################
Execution without init...
26.249463081359863
[[0 4 2 3 5 6 7 8 9 1]
 [0 4 2 3 5 6 7 9 1 8]
 [0 4 2 3 5 6 7 9 8 1]
 [0 4 2 3 5 6 9 7 1 8]
 [0 4 2 3 5 6 9 7 8 1]
 [0 4 2 3 5 7 6 8 9 1]
 [0 4 2 3 5 7 6 9 1 8]
 [0 4 2 3 5 7 6 9 8 1]
 [0 4 2 3 6 5 7 8 9 1]
 [0 4 2 3 6 5 7 9 1 8]
 [0 4 2 3 6 5 7 9 8 1]
 [0 4 2 3 6 5 9 7 1 8]
 [0 4 2 3 6 5 9 7 8 1]
 [0 4 2 3 6 7 5 8 9 1]
 [0 4 2 3 6 7 5 9 1 8]
 [0 4 2 3 6 7 5 9 8 1]
 [0 4 2 3 7 5 6 8 9 1]
 [0 4 2 3 7 5 6 9 1 8]
 [0 4 2 3 7 5 6 9 8 1]
 [0 4 2 3 7 6 5 8 9 1]
 [0 4 2 3 7 6 5 9 1 8]
 [0 4 2 3 7 6 5 9 8 1]
 [0 4 2 5 3 6 7 8 9 1]
 [0 4 2 5 3 6 7 9 1 8]
 [0 4 2 5 3 6 7 9 8 1]
 [0 4 2 5 3 6 9 7 1 8]
 [0 4 2 5 3 6 9 7 8 1]
 [0 4 2 5 3 7 6 8 9 1]
 [0 4 2 5 3 7 6 9 1 8]
 [0 4 2 5 3 7 6 9 8 1]
 [0 4 5 2 3 6 7 8 9 1]
 [0 4 5 2

In [140]:
pd.DataFrame(results11).to_csv("results11_kemeny.csv")

In [141]:
results11

array([[11, None, 4.0, 36.0, 291.0, 5.5, 22.0, 19.669431924819946,
        17.753665924072266, 163, 165,
        '[9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]'],
       [11, None, 4.0, 28.0, 272.0, 3.1666666666666665,
        18.666666666666664, 40.24400997161865, 40.76507091522217, 182,
        186,
        '[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1\n 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1\n 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]'],
       [11, None, 5.0, 37.0, 284.0, 5.833333333333333,
        26.833333333333332, 18.584892988204956, 18.383450269699097, 166,
        172, '[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]'],
       [11, None, 6.0, 35.0, 284.0, 4.0, 18.0, 18.289226055145264,
        16.307510137557983, 166, 166, '[1. 1. 7. 7. 7. 7. 7. 7.]'],
       [11, None, 7.0, 32.0, 268.0, 5.2, 22.8, 64.4389419555664,
        62.850679874420166, 190, 202, '[6 6 7 7 7 7 8 8 8 8 8 8 8 8]'],
       [11, None, 5.0, 38.0, 300.0, 4.333333

In [143]:
results11 = np.zeros(0).reshape(0,12)
print('## 1 ########################')
om = np.array([
[0,3,9,9,4,6,6,6,6,6,8],
[7,0,8,8,6,6,7,6,6,7,6],
[1,2,0,6,3,2,2,2,1,3,4],
[1,2,4,0,2,5,4,3,2,5,2],
[6,4,7,8,0,6,7,7,4,8,7],
[4,4,8,5,4,0,4,6,5,6,5],
[4,3,8,6,3,6,0,7,4,5,5],
[4,4,8,7,3,4,3,0,3,7,5],
[4,4,9,8,6,5,6,7,0,9,5],
[4,3,7,5,2,4,5,3,1,0,4],
[2,4,6,8,3,5,5,5,5,6,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))
print('## 2 ########################')
om = np.array([
[0,3,6,3,5,4,4,5,6,6,4],
[7,0,6,6,5,5,5,6,9,7,8],
[4,4,0,4,6,7,5,5,7,7,4],
[7,4,6,0,4,5,5,4,6,6,5],
[5,5,4,6,0,5,5,3,7,7,6],
[6,5,3,5,5,0,5,5,7,7,5],
[6,5,5,5,5,5,0,3,7,6,6],
[5,4,5,6,7,5,7,0,6,7,6],
[4,1,3,4,3,3,3,4,0,4,3],
[4,3,3,4,3,3,4,3,6,0,4],
[6,2,6,5,4,5,4,4,7,6,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))
print('## 3 ########################')
om = np.array([
[0,4,5,6,3,4,5,4,6,6,5],
[6,0,7,7,5,5,6,6,6,7,5],
[5,3,0,6,2,2,3,4,5,4,4],
[4,3,4,0,5,5,3,5,6,5,3],
[7,5,8,5,0,3,5,6,5,4,4],
[6,5,8,5,7,0,6,6,6,6,5],
[5,4,7,7,5,4,0,5,6,5,6],
[6,4,6,5,4,4,5,0,6,5,5],
[4,4,5,4,5,4,4,4,0,6,4],
[4,3,6,5,6,4,5,5,4,0,6],
[5,5,6,7,6,5,4,5,6,4,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))
print('## 4 ########################')
om = np.array([
[0,3,4,5,5,6,6,7,4,5,4],
[7,0,7,7,5,6,8,6,6,5,7],
[6,3,0,8,4,9,10,6,5,4,5],
[5,3,2,0,3,8,6,4,4,2,3],
[5,5,6,7,0,9,8,8,6,5,6],
[4,4,1,2,1,0,5,4,3,2,2],
[4,2,0,4,2,5,0,4,2,2,4],
[3,4,4,6,2,6,6,0,5,3,4],
[6,4,5,6,4,7,8,5,0,6,6],
[5,5,6,8,5,8,8,7,4,0,7],
[6,3,5,7,4,8,6,6,4,3,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))
print('## 5 ########################')
om = np.array([
[0,8,8,7,7,9,6,7,6,8,7],
[2,0,5,5,5,6,5,5,4,6,7],
[2,5,0,6,4,5,2,5,4,5,6],
[3,5,4,0,4,5,6,5,4,5,7],
[3,5,6,6,0,5,4,6,5,6,7],
[1,4,5,5,5,0,4,5,4,4,4],
[4,5,8,4,6,6,0,5,3,6,4],
[3,5,5,5,4,5,5,0,3,5,5],
[4,6,6,6,5,6,7,7,0,8,6],
[2,4,5,5,4,6,4,5,2,0,7],
[3,3,4,3,3,6,6,5,4,3,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))
print('## 6 ########################')
om = np.array([
[0,8,10,6,6,8,8,7,8,9,8],
[2,0,6,1,4,6,4,3,4,6,6],
[0,4,0,2,3,4,2,1,3,5,5],
[4,9,8,0,5,7,8,6,7,8,7],
[4,6,7,5,0,7,6,7,6,6,6],
[2,4,6,3,3,0,4,6,4,6,7],
[2,6,8,2,4,6,0,6,4,6,6],
[3,7,9,4,3,4,4,0,6,7,5],
[2,6,7,3,4,6,6,4,0,7,6],
[1,4,5,2,4,4,4,3,3,0,6],
[2,4,5,3,4,3,4,5,4,4,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))
print('## 7 ########################')
om = np.array([
[0,2,3,5,5,3,4,4,4,3,4],
[8,0,5,9,5,5,7,6,8,4,6],
[7,5,0,8,6,5,5,7,8,5,6],
[5,1,2,0,4,3,5,5,6,4,3],
[5,5,4,6,0,6,6,8,7,8,5],
[7,5,5,7,4,0,4,7,6,7,5],
[6,3,5,5,4,6,0,6,6,6,4],
[6,4,3,5,2,3,4,0,5,3,5],
[6,2,2,4,3,4,4,5,0,3,5],
[7,6,5,6,2,3,4,7,7,0,5],
[6,4,4,7,5,5,6,5,5,5,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))
print('## 8 ########################')
om = np.array([
[0,1,4,5,3,4,2,5,2,6,3],
[9,0,6,7,7,6,7,7,6,7,4],
[6,4,0,5,4,4,3,6,3,6,3],
[5,3,5,0,3,3,3,5,2,6,3],
[7,3,6,7,0,4,4,6,3,7,3],
[6,4,6,7,6,0,6,9,5,7,4],
[8,3,7,7,6,4,0,6,3,7,3],
[5,3,4,5,4,1,4,0,2,4,2],
[8,4,7,8,7,5,7,8,0,6,5],
[4,3,4,4,3,3,3,6,4,0,3],
[7,6,7,7,7,6,7,8,5,7,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))
print('## 9 ########################')
om = np.array([
[0,5,3,5,5,5,5,3,4,3,5],
[5,0,5,5,7,7,7,6,5,3,6],
[7,5,0,5,5,5,5,4,7,5,5],
[5,5,5,0,7,5,7,3,4,3,6],
[5,3,5,3,0,5,6,3,5,3,7],
[5,3,5,5,5,0,5,3,5,4,6],
[5,3,5,3,4,5,0,4,5,3,6],
[7,4,6,7,7,7,6,0,6,5,6],
[6,5,3,6,5,5,5,4,0,5,6],
[7,7,5,7,7,6,7,5,5,0,7],
[5,4,5,4,3,4,4,4,4,3,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))
print('## 10 ########################')
om = np.array([
[0,4,7,6,2,3,5,3,2,4,5],
[6,0,7,6,3,6,7,6,3,5,6],
[3,3,0,4,3,3,4,3,3,4,4],
[4,4,6,0,2,4,6,6,5,4,5],
[8,7,7,8,0,5,8,8,6,7,7],
[7,4,7,6,5,0,8,6,6,4,4],
[5,3,6,4,2,2,0,6,4,5,5],
[7,4,7,4,2,4,4,0,4,6,3],
[8,7,7,5,4,4,6,6,0,6,6],
[6,5,6,6,3,6,5,4,4,0,4],
[5,4,6,5,3,6,5,7,4,6,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))

## 1 ########################
Execution without init...
52.93451285362244
[[ 1  0  8  4  6  5  7 10  9  2  3]
 [ 1  0  8  4  6  5 10  7  9  2  3]
 [ 1  0  8  4  6 10  5  7  9  2  3]
 [ 1  0  8  4 10  6  5  7  9  2  3]
 [ 1  4  0  8  6  5  7 10  9  2  3]
 [ 1  4  0  8  6  5 10  7  9  2  3]
 [ 1  4  0  8  6 10  5  7  9  2  3]
 [ 1  4  0  8 10  6  5  7  9  2  3]
 [ 1  4  0 10  8  6  5  7  9  2  3]
 [ 1  8  4  0  6  5  7 10  9  2  3]
 [ 1  8  4  0  6  5 10  7  9  2  3]
 [ 1  8  4  0  6 10  5  7  9  2  3]
 [ 1  8  4  0 10  6  5  7  9  2  3]]
Obtained distance is [186]
[ 1  0  9 10  3  5  4  6  2  8  7]
Execution with borda... (distance = [190])
[ 2  0 10  9  1  4  5  7  3  8  6]
51.1645827293396
[[ 1  0  8  4  6  5  7 10  9  2  3]
 [ 1  0  8  4  6  5 10  7  9  2  3]
 [ 1  0  8  4  6 10  5  7  9  2  3]
 [ 1  0  8  4 10  6  5  7  9  2  3]
 [ 1  4  0  8  6  5  7 10  9  2  3]
 [ 1  4  0  8  6  5 10  7  9  2  3]
 [ 1  4  0  8  6 10  5  7  9  2  3]
 [ 1  4  0  8 10  6  5  7  9  2  3]
 [ 1  4  0 1

55.12371516227722
[[ 0  3  4  6  7  8  1  5  2  9 10]
 [ 0  3  4  6  7  8  1  5  9  2 10]
 [ 0  3  4  6  7  8  1  5  9 10  2]
 [ 0  3  4  7  8  6  1  5  2  9 10]
 [ 0  3  4  7  8  6  1  5  9  2 10]
 [ 0  3  4  7  8  6  1  5  9 10  2]
 [ 0  3  4  8  6  5  7  1  2  9 10]
 [ 0  3  4  8  6  5  7  1  9  2 10]
 [ 0  3  4  8  6  5  7  1  9 10  2]
 [ 0  3  4  8  6  7  1  5  2  9 10]
 [ 0  3  4  8  6  7  1  5  9  2 10]
 [ 0  3  4  8  6  7  1  5  9 10  2]
 [ 0  4  3  6  7  8  1  5  2  9 10]
 [ 0  4  3  6  7  8  1  5  9  2 10]
 [ 0  4  3  6  7  8  1  5  9 10  2]
 [ 0  4  3  7  8  6  1  5  2  9 10]
 [ 0  4  3  7  8  6  1  5  9  2 10]
 [ 0  4  3  7  8  6  1  5  9 10  2]
 [ 0  4  3  8  6  5  7  1  2  9 10]
 [ 0  4  3  8  6  5  7  1  9  2 10]
 [ 0  4  3  8  6  5  7  1  9 10  2]
 [ 0  4  3  8  6  7  1  5  2  9 10]
 [ 0  4  3  8  6  7  1  5  9  2 10]
 [ 0  4  3  8  6  7  1  5  9 10  2]]
Obtained distance is [185]
[ 0  6  8  1  2  7  3  4  5  9 10]
Execution with borda... (distance = [189])
[ 0  7 10  1

In [144]:
results11

array([[11, None, 6.0, 47.0, 366.0, 5.333333333333333,
        30.833333333333332, 52.93451285362244, 51.1645827293396, 186,
        190, '[1 1 1 1 1 1 1 1 1 1 1 1 1]'],
       [11, None, 7.0, 40.0, 335.0, 4.7, 21.0, 227.915953874588,
        212.10705399513245, 219, 221, '[1 1 1 1 1 1 1 1 1 1]'],
       [11, None, 6.0, 37.0, 324.0, 1.5833333333333333,
        8.166666666666666, 366.2616949081421, 358.83891916275024, 230,
        236, '[1 1 1 1 5 5 5 5]'],
       [11, None, 6.0, 45.0, 360.0, 5.0, 29.0, 65.2433009147644,
        60.37377405166626, 190, 192, '[1 1 1 1 4 4 4 4]'],
       [11, None, 5.0, 38.0, 336.0, 5.75, 36.25, 219.79064989089966,
        218.9953510761261, 218, 224,
        '[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n 0 0 0 0]'],
       [11, None, 6.0, 51.0, 369.0, 3.833333333333333,
        23.166666666666668, 55.12371516227722, 52.43206286430359, 185,
        1

In [145]:
pd.DataFrame(results11).to_csv("results11_kemeny.csv")

In [146]:
print('## 1 ########################')
om = np.array([
[0,6,2,6,8,3,3,3,3,3,5],
[4,0,6,3,7,5,5,4,4,4,6],
[8,4,0,6,8,6,5,8,3,4,4],
[4,7,4,0,7,5,7,4,6,2,7],
[2,3,2,3,0,3,3,0,0,0,3],
[7,5,4,5,7,0,2,6,7,3,5],
[7,5,5,3,7,8,0,7,7,3,5],
[7,6,2,6,10,4,3,0,3,4,6],
[7,6,7,4,10,3,3,7,0,3,7],
[7,6,6,8,10,7,7,6,7,0,8],
[5,4,6,3,7,5,5,4,3,2,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))

print('## 2 ########################')
om = np.array([
[0,7,6,3,3,3,6,4,4,5,1],
[3,0,6,5,5,3,8,4,4,5,1],
[4,4,0,4,4,7,7,4,4,6,4],
[7,5,6,0,9,6,5,3,7,7,5],
[7,5,6,1,0,3,6,4,4,4,0],
[7,7,3,4,7,0,7,5,5,7,5],
[4,2,3,5,4,3,0,3,4,6,2],
[6,6,6,7,6,5,7,0,4,4,4],
[6,6,6,3,6,5,6,6,0,10,6],
[5,5,4,3,6,3,4,6,0,0,2],
[9,9,6,5,10,5,8,6,4,8,0]])

print('## 3 ########################')
om = np.array([
[0,5,4,3,6,2,4,3,5,4,2],
[5,0,4,5,7,2,4,4,4,1,2],
[6,6,0,6,6,4,3,4,6,3,3],
[7,5,4,0,6,4,6,6,3,6,6],
[4,3,4,4,0,3,4,3,1,3,5],
[8,8,6,6,7,0,8,7,5,8,8],
[6,6,7,4,6,2,0,8,4,7,4],
[7,6,6,4,7,3,2,0,3,2,3],
[5,6,4,7,9,5,6,7,0,5,5],
[6,9,7,4,7,2,3,8,5,0,2],
[8,8,7,4,5,2,6,7,5,8,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))

print('## 4 ########################')
om = np.array([
[0,4,4,4,4,4,4,6,6,4,6],
[6,0,4,6,6,4,4,8,8,4,4],
[6,6,0,6,6,8,10,8,10,8,6],
[6,4,4,0,4,2,4,6,4,4,4],
[6,4,4,6,0,4,6,6,6,4,6],
[6,6,2,8,6,0,2,6,4,4,4],
[6,6,0,6,4,8,0,8,8,8,6],
[4,2,2,4,4,4,2,0,4,6,2],
[4,2,0,6,4,6,2,6,0,6,4],
[6,6,2,6,6,6,2,4,4,0,4],
[4,6,4,6,4,6,4,8,6,6,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))

print('## 5 ########################')
om = np.array([
[0,5,7,4,4,7,5,5,5,7,5],
[5,0,7,4,3,4,2,5,4,4,5],
[3,3,0,2,3,4,3,3,3,4,4],
[6,6,8,0,3,6,6,7,5,6,7],
[6,7,7,7,0,6,6,6,5,6,8],
[3,6,6,4,4,0,2,3,4,6,6],
[5,8,7,4,4,8,0,7,7,8,8],
[5,5,7,3,4,7,3,0,4,7,5],
[5,6,7,5,5,6,3,6,0,6,6],
[3,6,6,4,4,4,2,3,4,0,4],
[5,5,6,3,2,4,2,5,4,6,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))

print('## 6 ########################')
om = np.array([
[0,8,4,5,7,8,6,7,2,5,4],
[2,0,2,3,5,6,4,5,3,4,1],
[6,8,0,5,8,7,9,7,7,6,3],
[5,7,5,0,7,8,8,6,6,7,5],
[3,5,2,3,0,4,3,5,2,2,1],
[2,4,3,2,6,0,3,5,0,3,0],
[4,6,1,2,7,7,0,5,5,1,2],
[3,5,3,4,5,5,5,0,3,4,3],
[8,7,3,4,8,10,5,7,0,5,5],
[5,6,4,3,8,7,9,6,5,0,4],
[6,9,7,5,9,10,8,7,5,6,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))

print('## 7 ########################')
om = np.array([
[0,5,3,2,0,2,2,0,5,2,5],
[5,0,3,5,0,5,0,0,5,0,5],
[7,7,0,7,5,7,2,0,7,7,7],
[8,5,3,0,3,8,5,3,8,3,5],
[10,10,5,7,0,10,5,5,10,7,7],
[8,5,3,2,0,0,2,0,5,2,5],
[8,10,8,5,5,8,0,8,8,5,5],
[10,10,10,7,5,10,2,0,10,7,7],
[5,5,3,2,0,5,2,0,0,0,5],
[8,10,3,7,3,8,5,3,10,0,5],
[5,5,3,5,3,5,5,3,5,5,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))

print('## 8 ########################')
om = np.array([
[0,3,2,6,4,7,5,6,4,7,5],
[7,0,4,6,4,8,4,6,2,5,6],
[8,6,0,8,6,9,6,6,5,8,7],
[4,4,2,0,5,6,5,6,3,5,5],
[6,6,4,5,0,6,5,5,4,7,5],
[3,2,1,4,4,0,3,2,1,7,5],
[5,6,4,5,5,7,0,7,3,8,2],
[4,4,4,4,5,8,3,0,2,6,4],
[6,8,5,7,6,9,7,8,0,8,7],
[3,5,2,5,3,3,2,4,2,0,1],
[5,4,3,5,5,5,8,6,3,9,0]])
results11 = np.vstack((results11, measure(11,0,rep=1,om=om)))

## 1 ########################
Execution without init...
78.32724905014038
[[ 9  2  3  6  5  8  7  0  1 10  4]
 [ 9  3  6  5  8  2  7  0  1 10  4]
 [ 9  6  5  8  2  7  0  3  1 10  4]]
Obtained distance is [191]
[ 7  8  1  2 10  4  3  6  5  0  9]
Execution with borda... (distance = [199])
[ 9  7  3  4 10  5  1  6  2  0  8]
66.88887691497803
[[ 9  2  3  6  5  8  7  0  1 10  4]
 [ 9  3  6  5  8  2  7  0  1 10  4]
 [ 9  6  5  8  2  7  0  3  1 10  4]]
## 2 ########################
## 3 ########################
Execution without init...
74.68679785728455
[[ 5  8  3 10  6  9  7  2  0  1  4]
 [ 5  8  3 10  6  9  7  2  1  0  4]
 [ 8  5  3 10  6  9  7  2  0  1  4]
 [ 8  5  3 10  6  9  7  2  1  0  4]]
Obtained distance is [191]
[ 8  9  7  2 10  0  4  6  1  5  3]
Execution with borda... (distance = [197])
[ 8  9  6  4 10  0  3  7  2  5  1]
54.121251821517944
[[ 5  8  3 10  6  9  7  2  0  1  4]
 [ 5  8  3 10  6  9  7  2  1  0  4]
 [ 8  5  3 10  6  9  7  2  0  1  4]
 [ 8  5  3 10  6  9  7  2  1  0  4

In [147]:
results11

array([[11, None, 6.0, 47.0, 366.0, 5.333333333333333,
        30.833333333333332, 52.93451285362244, 51.1645827293396, 186,
        190, '[1 1 1 1 1 1 1 1 1 1 1 1 1]'],
       [11, None, 7.0, 40.0, 335.0, 4.7, 21.0, 227.915953874588,
        212.10705399513245, 219, 221, '[1 1 1 1 1 1 1 1 1 1]'],
       [11, None, 6.0, 37.0, 324.0, 1.5833333333333333,
        8.166666666666666, 366.2616949081421, 358.83891916275024, 230,
        236, '[1 1 1 1 5 5 5 5]'],
       [11, None, 6.0, 45.0, 360.0, 5.0, 29.0, 65.2433009147644,
        60.37377405166626, 190, 192, '[1 1 1 1 4 4 4 4]'],
       [11, None, 5.0, 38.0, 336.0, 5.75, 36.25, 219.79064989089966,
        218.9953510761261, 218, 224,
        '[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n 0 0 0 0]'],
       [11, None, 6.0, 51.0, 369.0, 3.833333333333333,
        23.166666666666668, 55.12371516227722, 52.43206286430359, 185,
        1

In [148]:
pd.DataFrame(results11).to_csv("results11_kemeny.csv")

In [151]:
results12 = np.zeros(0).reshape(0,12)
print('## 1 ########################')
om = np.array([
[0,5,7,6,2,5,6,5,8,6,4,7],
[5,0,6,6,3,7,8,6,7,6,4,6],
[3,4,0,7,3,6,3,5,5,6,2,4],
[4,4,3,0,3,2,2,2,4,3,4,3],
[8,7,7,7,0,8,6,8,9,5,4,8],
[5,3,4,8,2,0,3,2,5,3,5,4],
[4,2,7,8,4,7,0,7,4,5,4,7],
[5,4,5,8,2,8,3,0,6,3,5,6],
[2,3,5,6,1,5,6,4,0,6,1,5],
[4,4,4,7,5,7,5,7,4,0,3,4],
[6,6,8,6,6,5,6,5,9,7,0,9],
[3,4,6,7,2,6,3,4,5,6,1,0]])
results12 = np.vstack((results12, measure(12,0,rep=1,om=om)))
print('## 2 ########################')
om = np.array([
[0,6,9,7,5,6,6,6,7,8,6,6],
[4,0,8,7,4,6,5,9,8,6,6,6],
[1,2,0,3,3,4,4,7,3,0,3,5],
[3,3,7,0,4,3,5,8,5,5,6,5],
[5,6,7,6,0,7,3,7,7,7,8,4],
[4,4,6,7,3,0,4,7,5,5,5,5],
[4,5,6,5,7,6,0,8,5,6,7,6],
[4,1,3,2,3,3,2,0,4,3,5,4],
[3,2,7,5,3,5,5,6,0,5,5,4],
[2,4,10,5,3,5,4,7,5,0,3,7],
[4,4,7,4,2,5,3,5,5,7,0,5],
[4,4,5,5,6,5,4,6,6,3,5,0]])
results12 = np.vstack((results12, measure(12,0,rep=1,om=om)))
print('## 3 ########################')
om = np.array([
[0,9,5,5,10,10,10,4,5,4,5,10],
[1,0,5,5,10,5,10,0,5,4,5,5],
[5,5,0,5,9,10,10,5,10,5,5,10],
[5,5,5,0,9,10,10,5,5,5,5,10],
[0,0,1,1,0,1,6,0,1,0,1,1],
[0,5,0,0,9,0,5,0,0,0,0,10],
[0,0,0,0,4,5,0,0,0,0,0,5],
[6,10,5,5,10,10,10,0,10,9,10,10],
[5,5,0,5,9,10,10,0,0,5,5,10],
[6,6,5,5,10,10,10,1,5,0,5,10],
[5,5,5,5,9,10,10,0,5,5,0,10],
[0,5,0,0,9,0,5,0,0,0,0,0]])
results12 = np.vstack((results12, measure(12,0,rep=1,om=om)))
print('## 4 ########################')
om = np.array([
[0,7,5,7,6,8,5,6,7,5,5,7],
[3,0,5,9,7,7,6,7,7,7,7,8],
[5,5,0,5,7,7,9,5,7,7,6,6],
[3,1,5,0,6,4,5,4,5,5,5,4],
[4,3,3,4,0,5,5,3,4,6,3,3],
[2,3,3,6,5,0,6,2,4,4,3,6],
[5,4,1,5,5,4,0,3,5,6,4,4],
[4,3,5,6,7,8,7,0,7,7,6,7],
[3,3,3,5,6,6,5,3,0,7,7,5],
[5,3,3,5,4,6,4,3,3,0,4,4],
[5,3,4,5,7,7,6,4,3,6,0,6],
[3,2,4,6,7,4,6,3,5,6,4,0]])
results12 = np.vstack((results12, measure(12,0,rep=1,om=om)))
print('## 5 ########################')
om = np.array([
[0,5,8,10,6,9,10,6,5,6,9,8],
[5,0,10,10,4,7,10,6,4,7,7,9],
[2,0,0,6,0,4,7,5,3,2,5,5],
[0,0,4,0,3,4,6,3,2,4,3,0],
[4,6,10,7,0,8,10,7,4,7,7,6],
[1,3,6,6,2,0,5,4,3,1,4,5],
[0,0,3,4,0,5,0,2,2,1,3,2],
[4,4,5,7,3,6,8,0,7,4,5,4],
[5,6,7,8,6,7,8,3,0,4,7,5],
[4,3,8,6,3,9,9,6,6,0,9,6],
[1,3,5,7,3,6,7,5,3,1,0,5],
[2,1,5,10,4,5,8,6,5,4,5,0]])
results12 = np.vstack((results12, measure(12,0,rep=1,om=om)))
print('## 6 ########################')
om = np.array([
[0,2,4,2,1,2,3,4,3,4,1,6],
[8,0,7,6,3,2,3,6,5,5,3,7],
[6,3,0,6,3,1,4,4,4,3,3,3],
[8,4,4,0,6,3,5,5,5,5,5,5],
[9,7,7,4,0,5,3,8,6,7,5,9],
[8,8,9,7,5,0,4,8,6,9,8,9],
[7,7,6,5,7,6,0,6,7,7,6,7],
[6,4,6,5,2,2,4,0,4,2,4,3],
[7,5,6,5,4,4,3,6,0,7,7,7],
[6,5,7,5,3,1,3,8,3,0,6,6],
[9,7,7,5,5,2,4,6,3,4,0,5],
[4,3,7,5,1,1,3,7,3,4,5,0]])
results12 = np.vstack((results12, measure(12,0,rep=1,om=om)))
print('## 7 ########################')
om = np.array([
[0,6,5,5,5,4,4,2,3,8,4,6],
[4,0,6,8,8,6,3,5,6,8,5,5],
[5,4,0,5,7,4,3,3,7,6,3,8],
[5,2,5,0,6,1,3,3,4,8,1,5],
[5,2,3,4,0,3,4,2,2,5,2,6],
[6,4,6,9,7,0,3,5,7,8,6,6],
[6,7,7,7,6,7,0,6,5,6,5,5],
[8,5,7,7,8,5,4,0,8,8,8,5],
[7,4,3,6,8,3,5,2,0,8,5,7],
[2,2,4,2,5,2,4,2,2,0,2,5],
[6,5,7,9,8,4,5,2,5,8,0,6],
[4,5,2,5,4,4,5,5,3,5,4,0]])
results12 = np.vstack((results12, measure(12,0,rep=1,om=om)))
print('## 8 ########################')
om = np.array([
[0,5,4,8,8,6,6,7,7,4,5,10],
[5,0,2,8,6,7,4,4,8,4,4,8],
[6,8,0,9,10,10,8,5,10,7,6,10],
[2,2,1,0,2,5,2,2,7,1,2,5],
[2,4,0,8,0,5,2,2,7,3,4,8],
[4,3,0,5,5,0,3,3,7,2,2,5],
[4,6,2,8,8,7,0,5,7,5,4,9],
[3,6,5,8,8,7,5,0,6,5,3,9],
[3,2,0,3,3,3,3,4,0,1,2,4],
[6,6,3,9,7,8,5,5,9,0,5,9],
[5,6,4,8,6,8,6,7,8,5,0,8],
[0,2,0,5,2,5,1,1,6,1,2,0]])
results12 = np.vstack((results12, measure(12,0,rep=1,om=om)))
print('## 9 ########################')
om = np.array([
[0,3,3,5,5,2,5,4,3,7,2,3],
[7,0,4,9,4,5,6,3,6,7,4,5],
[7,6,0,7,3,2,6,4,5,8,2,6],
[5,1,3,0,3,1,3,4,6,4,2,3],
[5,6,7,7,0,5,7,5,7,8,6,4],
[8,5,8,9,5,0,5,5,8,8,4,6],
[5,4,4,7,3,5,0,3,5,6,4,2],
[6,7,6,6,5,5,7,0,6,5,5,7],
[7,4,5,4,3,2,5,4,0,8,3,3],
[3,3,2,6,2,2,4,5,2,0,1,4],
[8,6,8,8,4,6,6,5,7,9,0,7],
[7,5,4,7,6,4,8,3,7,6,3,0]])
results12 = np.vstack((results12, measure(12,0,rep=1,om=om)))
print('## 10 ########################')
om = np.array([
[0,7,5,5,6,7,5,6,7,2,7,4],
[3,0,4,1,4,5,1,3,8,3,5,1],
[5,6,0,5,8,7,5,3,9,5,7,5],
[5,9,5,0,5,4,4,5,9,5,7,3],
[4,6,2,5,0,4,3,2,5,3,5,2],
[3,5,3,6,6,0,4,4,8,4,8,2],
[5,9,5,6,7,6,0,6,9,4,8,4],
[4,7,7,5,8,6,4,0,9,4,7,3],
[3,2,1,1,5,2,1,1,0,4,4,1],
[8,7,5,5,7,6,6,6,6,0,7,6],
[3,5,3,3,5,2,2,3,6,3,0,0],
[6,9,5,7,8,8,6,7,9,4,10,0]])
results12 = np.vstack((results12, measure(12,0,rep=1,om=om)))

## 1 ########################
Execution without init...
396.8952100276947
[[10  4  0  1  8  6 11  2  9  7  5  3]
 [10  4  1  0  8  6 11  2  9  7  5  3]]
Obtained distance is [231]
[ 2  3  7 11  1 10  5  9  4  8  0  6]
Execution with borda... (distance = [243])
[ 3  2  7 11  0  9  4  5 10  6  1  8]
390.5163118839264
[[10  4  0  1  8  6 11  2  9  7  5  3]
 [10  4  1  0  8  6 11  2  9  7  5  3]]
## 2 ########################
Execution without init...
527.6118531227112
[[ 0  6  4  1  5  3 10  9 11  8  2  7]]
Obtained distance is [241]
[ 0  3 10  5  2  4  1 11  9  7  6  8]
Execution with borda... (distance = [251])
[ 0  1 10  6  2  4  3 11  9  5  8  7]
525.6951186656952
[[ 0  6  4  1  5  3 10  9 11  8  2  7]]
## 3 ########################
Execution without init...
41.20934295654297
[[ 2  3  7 ... 11  4  6]
 [ 2  3  7 ... 11  4  6]
 [ 2  3  7 ... 11  4  6]
 ...
 [ 7 10  9 ... 11  4  6]
 [ 7 10  9 ... 11  4  6]
 [ 7 10  9 ...  1  4  6]]
Obtained distance is [139]
[ 5  6  0  1 10  8 11  2  3  

511.00723576545715
[[ 4  7 10  5  2  1 11  6  3  8  0  9]
 [ 4  7 10  5  2  1 11  6  8  0  9  3]
 [ 4  7 10  5  2  1 11  8  0  6  9  3]
 [ 4  7 10  5  2  1 11  8  6  0  9  3]
 [ 4  7 10  5  2 11  1  6  3  8  0  9]
 [ 4  7 10  5  2 11  1  6  8  0  9  3]
 [ 4  7 10  5  2 11  1  8  0  6  9  3]
 [ 4  7 10  5  2 11  1  8  6  0  9  3]
 [ 4 10  5  7  2  1 11  6  3  8  0  9]
 [ 4 10  5  7  2  1 11  6  8  0  9  3]
 [ 4 10  5  7  2  1 11  8  0  6  9  3]
 [ 4 10  5  7  2  1 11  8  6  0  9  3]
 [ 4 10  5  7  2 11  1  6  3  8  0  9]
 [ 4 10  5  7  2 11  1  6  8  0  9  3]
 [ 4 10  5  7  2 11  1  8  0  6  9  3]
 [ 4 10  5  7  2 11  1  8  6  0  9  3]
 [ 4 10  7  5  2  1 11  6  3  8  0  9]
 [ 4 10  7  5  2  1 11  6  8  0  9  3]
 [ 4 10  7  5  2  1 11  8  0  6  9  3]
 [ 4 10  7  5  2  1 11  8  6  0  9  3]
 [ 4 10  7  5  2 11  1  6  3  8  0  9]
 [ 4 10  7  5  2 11  1  6  8  0  9  3]
 [ 4 10  7  5  2 11  1  8  0  6  9  3]
 [ 4 10  7  5  2 11  1  8  6  0  9  3]
 [ 7  4 10  5  2  1 11  6  3  8  0  9]
 [ 7  

In [152]:
results11

array([[11, None, 6.0, 47.0, 366.0, 5.333333333333333,
        30.833333333333332, 52.93451285362244, 51.1645827293396, 186,
        190, '[1 1 1 1 1 1 1 1 1 1 1 1 1]'],
       [11, None, 7.0, 40.0, 335.0, 4.7, 21.0, 227.915953874588,
        212.10705399513245, 219, 221, '[1 1 1 1 1 1 1 1 1 1]'],
       [11, None, 6.0, 37.0, 324.0, 1.5833333333333333,
        8.166666666666666, 366.2616949081421, 358.83891916275024, 230,
        236, '[1 1 1 1 5 5 5 5]'],
       [11, None, 6.0, 45.0, 360.0, 5.0, 29.0, 65.2433009147644,
        60.37377405166626, 190, 192, '[1 1 1 1 4 4 4 4]'],
       [11, None, 5.0, 38.0, 336.0, 5.75, 36.25, 219.79064989089966,
        218.9953510761261, 218, 224,
        '[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n 0 0 0 0]'],
       [11, None, 6.0, 51.0, 369.0, 3.833333333333333,
        23.166666666666668, 55.12371516227722, 52.43206286430359, 185,
        1

In [153]:
pd.DataFrame(results12).to_csv("results12_kemeny.csv")

In [154]:
results12

array([[12, None, 6.0, 55.0, 433.0, 6.333333333333334, 33.83333333333333,
        396.8952100276947, 390.5163118839264, 231, 243, '[10 10]'],
       [12, None, 6.0, 50.0, 421.0, 5.25, 29.0, 527.6118531227112,
        525.6951186656952, 241, 251, '[0]'],
       [12, None, 8.0, 43.0, 521.0, 4.833333333333334,
        25.166666666666668, 41.20934295654297, 40.63276290893555, 139,
        143, '[2 2 2 ... 7 7 7]'],
       [12, None, 5.0, 51.0, 417.0, 5.25, 36.0, 592.3660159111023,
        592.9359459877014, 245, 261, '[0 0 0 0 0 0 0 0 0 2 2 2]'],
       [12, None, 7.0, 56.0, 467.0, 6.0, 29.0, 151.35706496238708,
        148.66073083877563, 197, 205, '[0]'],
       [12, None, 7.0, 55.0, 440.0, 6.75, 46.75, 452.22408509254456,
        311.94204115867615, 224, 230, '[6 6]'],
       [12, None, 7.0, 50.0, 431.0, 7.5, 36.5, 401.10931515693665,
        393.5462837219238, 231, 245,
        '[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]'],
       [12, None, 7.0, 55.0, 471.0, 6.333333333333333,


In [155]:
om = np.array([
[0,4,6,3,4,3,4,4],
[6,0,6,4,5,3,6,4],
[4,4,0,4,6,4,6,5],
[7,6,6,0,7,5,5,4],
[6,5,4,3,0,3,3,3],
[7,7,6,5,7,0,6,6],
[6,4,4,5,7,4,0,5],
[6,6,5,6,7,4,5,0]])
measure(8,0,rep=3,om=om)

Execution without init...
1.1321226755777996
[[5 7 3 1 2 6 4 0]]
Obtained distance is [112]
[7 3 4 2 6 0 5 1]
Execution with borda... (distance = [120])
[6 4 5 1 7 0 3 2]
1.0312405427296956
[[5 7 3 1 2 6 4 0]]


array([8, None, 4.0, 23.0, 170.0, 3.5, 16.0, 1.1321226755777996,
       1.0312405427296956, 112, 120, '[5]'], dtype=object)

In [159]:
om = np.array([
[0,8,8,8,6,7,5,9],
[2,0,2,6,1,2,1,2],
[2,8,0,8,4,4,3,6],
[2,4,2,0,2,3,2,3],
[4,9,6,8,0,5,7,9],
[3,8,6,7,5,0,5,7],
[5,9,7,8,3,5,0,8],
[1,8,4,7,1,3,2,0]])
print(measure(8,0,rep=3,om=om))

print('## 21 ########################')
om = np.array([
[0,5,5,8,2,5,5,8],
[5,0,2,7,3,5,7,5],
[5,8,0,10,3,5,10,8],
[2,3,0,0,0,5,4,5],
[8,7,7,10,0,8,7,10],
[5,5,5,5,2,0,5,8],
[5,3,0,6,3,5,0,8],
[2,5,2,5,0,2,2,0]])
print(measure(8,0,rep=3,om=om))
print('## 22 ########################')
om = np.array([
[0,5,10,5,9,7,9,8],
[5,0,6,5,9,4,5,5],
[0,4,0,3,9,6,7,5],
[5,5,7,0,7,5,9,7],
[1,1,1,3,0,3,4,4],
[3,6,4,5,7,0,5,7],
[1,5,3,1,6,5,0,6],
[2,5,5,3,6,3,4,0]])
print(measure(8,0,rep=3,om=om))
print('## 23 ########################')
om = np.array([
[0,6,10,3,4,5,6,2],
[4,0,5,4,1,5,2,3],
[0,5,0,3,2,2,0,0],
[7,6,7,0,4,3,4,4],
[6,9,8,6,0,7,6,6],
[5,5,8,7,3,0,4,2],
[4,8,10,6,4,6,0,5],
[8,7,10,6,4,8,5,0]])
print(measure(8,0,rep=3,om=om))
print('## 24 ########################')
om = np.array([
[0,7,8,8,8,6,6,9],
[3,0,5,7,3,6,6,6],
[2,5,0,7,5,5,6,9],
[2,3,3,0,5,7,4,3],
[2,7,5,5,0,6,6,7],
[4,4,5,3,4,0,5,5],
[4,4,4,6,4,5,0,5],
[1,4,1,7,3,5,5,0]])
print(measure(8,0,rep=3,om=om))
print('## 25 ########################')
om = np.array([
[0,7,5,4,9,4,4,7],
[3,0,7,5,5,6,3,5],
[5,3,0,5,6,5,3,5],
[6,5,5,0,7,6,2,7],
[1,5,4,3,0,3,4,3],
[6,4,5,4,7,0,4,6],
[6,7,7,8,6,6,0,7],
[3,5,5,3,7,4,3,0]])
print(measure(8,0,rep=3,om=om))
print('## 26 ########################')
om = np.array([
[0,8,7,4,7,5,7,5],
[2,0,4,5,3,5,5,6],
[3,6,0,4,5,5,5,4],
[6,5,6,0,4,2,4,2],
[3,7,5,6,0,5,4,4],
[5,5,5,8,5,0,6,3],
[3,5,5,6,6,4,0,2],
[5,4,6,8,6,7,8,0]])
print(measure(8,0,rep=3,om=om))
print('## 27 ########################')
om = np.array([
[0,1,5,2,3,1,5,1],
[9,0,8,5,6,8,6,6],
[5,2,0,3,2,3,3,1],
[8,5,7,0,3,6,7,5],
[7,4,8,7,0,5,9,8],
[9,2,7,4,5,0,4,5],
[5,4,7,3,1,6,0,1],
[9,4,9,5,2,5,9,0]])
print(measure(8,0,rep=3,om=om))

Execution without init...
0.18448368708292642
[[0 4 5 6 2 7 1 3]
 [0 4 6 5 2 7 1 3]
 [0 5 4 6 2 7 1 3]]
Obtained distance is [77]
[0 6 4 7 1 2 3 5]
Execution with borda... (distance = [79])
[0 7 4 6 1 3 2 5]
0.15132872263590494
[[0 4 5 6 2 7 1 3]
 [0 4 6 5 2 7 1 3]
 [0 5 4 6 2 7 1 3]]
[8 None 5.0 25.0 203.0 6.5 25.5 0.18448368708292642 0.15132872263590494 77
 79 '[0 0 0]']
## 21 ########################
Execution without init...
0.3283422787984212
[[4 0 2 1 5 6 3 7]
 [4 0 2 1 5 6 7 3]
 [4 0 2 1 6 3 5 7]
 [4 0 2 1 6 5 3 7]
 [4 0 2 1 6 5 7 3]
 [4 0 2 5 1 6 3 7]
 [4 0 2 5 1 6 7 3]
 [4 0 5 2 1 6 3 7]
 [4 0 5 2 1 6 7 3]
 [4 2 0 1 5 6 3 7]
 [4 2 0 1 5 6 7 3]
 [4 2 0 1 6 3 5 7]
 [4 2 0 1 6 5 3 7]
 [4 2 0 1 6 5 7 3]
 [4 2 0 5 1 6 3 7]
 [4 2 0 5 1 6 7 3]
 [4 2 1 0 5 6 3 7]
 [4 2 1 0 5 6 7 3]
 [4 2 1 0 6 3 5 7]
 [4 2 1 0 6 5 3 7]
 [4 2 1 0 6 5 7 3]
 [4 2 1 5 0 6 3 7]
 [4 2 1 5 0 6 7 3]
 [4 2 1 5 6 0 3 7]
 [4 2 1 5 6 0 7 3]
 [4 2 1 6 0 3 5 7]
 [4 2 1 6 0 5 3 7]
 [4 2 1 6 0 5 7 3]
 [4 2 1 6 5 0 3 

In [173]:
om = init.create_random_om(11, 10) 
measure(11,0,rep=3,om=om)

Execution without init...
41.759093364079796
[[ 7  9 10  5  6  8  2  1  3  0  4]]
Obtained distance is [177]
[ 9  7  6  8 10  3  4  0  5  1  2]
Execution with borda... (distance = [193])
[10  8  5  6  9  7  3  1  4  0  2]
30.052214701970417
[[ 7  9 10  5  6  8  2  1  3  0  4]]


array([11, None, 8.0, 52.0, 413.0, 4.583333333333334, 27.166666666666664,
       41.759093364079796, 30.052214701970417, 177, 193, '[7]'],
      dtype=object)

In [174]:
om = np.array([
[0,6,3,3,3,7,6,3,10,6,1],
[4,0,4,4,4,7,4,1,7,7,4],
[7,6,0,6,7,7,7,7,7,7,4],
[7,6,4,0,7,7,4,4,10,7,4],
[7,6,3,3,0,7,7,6,10,7,1],
[3,3,3,3,3,0,3,3,4,9,1],
[4,6,3,6,3,7,0,3,7,7,1],
[7,9,3,6,4,7,7,0,7,7,4],
[0,3,3,0,0,6,3,3,0,6,0],
[4,3,3,3,3,1,3,3,4,0,1],
[9,6,6,6,9,9,9,6,10,9,0]])
measure(11,0,rep=3,om=om)

Execution without init...
24.6334327061971
[[10  2  3  4  7  0  6  1  8  5  9]
 [10  2  7  3  4  0  6  1  8  5  9]]
Obtained distance is [160]
[ 5  7  1  2  3  9  6  4  8 10  0]
Execution with borda... (distance = [164])
[ 5  7  1  3  4  8  6  2 10  9  0]
17.139376004536945
[[10  2  3  4  7  0  6  1  8  5  9]
 [10  2  7  3  4  0  6  1  8  5  9]]


array([11, None, 5.0, 55.0, 394.0, 8.0, 45.0, 24.6334327061971,
       17.139376004536945, 160, 164, '[10 10]'], dtype=object)

In [176]:
om = np.array([
[0,2,2,2,1,1,0,2,2,1,4],
[8,0,1,3,4,4,1,3,5,2,6],
[8,9,0,3,4,5,1,4,6,7,6],
[8,7,7,0,6,4,1,5,7,6,6],
[9,6,6,4,0,5,0,5,6,5,7],
[9,6,5,6,5,0,4,7,7,6,5],
[10,9,9,9,10,6,0,9,7,9,7],
[8,7,6,5,5,3,1,0,6,5,5],
[8,5,4,3,4,3,3,4,0,4,6],
[9,8,3,4,5,4,1,5,6,0,7],
[6,4,4,4,3,5,3,5,4,3,0]])
measure(11,0,rep=3,om=om)

Execution without init...
74.37902720769246
[[ 6  5  3  4  7  2  9  1  8 10  0]
 [ 6  5  3  4  7  2  9  8  1 10  0]
 [ 6  5  3  7  4  2  9  1  8 10  0]
 [ 6  5  3  7  4  2  9  8  1 10  0]
 [ 6  5  7  3  4  2  9  1  8 10  0]
 [ 6  5  7  3  4  2  9  8  1 10  0]]
Obtained distance is [171]
[10  7  5  2  3  1  0  4  8  6  9]
Execution with borda... (distance = [177])
[10  9  3  2  4  1  0  6  7  5  8]
35.67982268333435
[[ 6  5  3  4  7  2  9  1  8 10  0]
 [ 6  5  3  4  7  2  9  8  1 10  0]
 [ 6  5  3  7  4  2  9  1  8 10  0]
 [ 6  5  3  7  4  2  9  8  1 10  0]
 [ 6  5  7  3  4  2  9  1  8 10  0]
 [ 6  5  7  3  4  2  9  8  1 10  0]]


array([11, None, 7.0, 46.0, 379.0, 6.5, 36.0, 74.37902720769246,
       35.67982268333435, 171, 177, '[6 6 6 6 6 6]'], dtype=object)

In [8]:
om = np.array([
[0,5,3,4,2,4,3,2,3,2,3],
[5,0,4,3,2,5,2,3,2,3,4],
[7,6,0,7,7,5,6,5,6,6,5],
[6,7,3,0,4,5,6,4,3,5,3],
[8,8,3,6,0,7,7,6,4,7,3],
[6,5,5,5,3,0,5,2,4,3,4],
[7,8,4,4,3,5,0,2,5,3,3],
[8,7,5,6,4,8,8,0,5,8,4],
[7,8,4,7,6,6,5,5,0,5,5],
[8,7,4,5,3,7,7,2,5,0,4],
[7,6,5,7,7,6,7,6,5,6,0]])
measure(11,0,rep=3,om=om)

Execution without init...
108.32043925921123
[[ 2  8 10  4  7  3  9  5  6  0  1]
 [ 2  8 10  4  7  3  9  5  6  1  0]
 [ 2  8 10  4  7  3  9  6  1  5  0]
 [ 2  8 10  4  7  3  9  6  5  0  1]
 [ 2  8 10  4  7  3  9  6  5  1  0]
 [ 2  8 10  4  7  9  3  5  6  0  1]
 [ 2  8 10  4  7  9  3  5  6  1  0]
 [ 2  8 10  4  7  9  3  6  1  5  0]
 [ 2  8 10  4  7  9  3  6  5  0  1]
 [ 2  8 10  4  7  9  3  6  5  1  0]
 [ 2  8 10  4  7  9  5  3  6  0  1]
 [ 2  8 10  4  7  9  5  3  6  1  0]
 [ 2 10  8  4  7  3  9  5  6  0  1]
 [ 2 10  8  4  7  3  9  5  6  1  0]
 [ 2 10  8  4  7  3  9  6  1  5  0]
 [ 2 10  8  4  7  3  9  6  5  0  1]
 [ 2 10  8  4  7  3  9  6  5  1  0]
 [ 2 10  8  4  7  9  3  5  6  0  1]
 [ 2 10  8  4  7  9  3  5  6  1  0]
 [ 2 10  8  4  7  9  3  6  1  5  0]
 [ 2 10  8  4  7  9  3  6  5  0  1]
 [ 2 10  8  4  7  9  3  6  5  1  0]
 [ 2 10  8  4  7  9  5  3  6  0  1]
 [ 2 10  8  4  7  9  5  3  6  1  0]
 [10  2  8  4  7  3  9  5  6  0  1]
 [10  2  8  4  7  3  9  5  6  1  0]
 [10  2  8  4  7  3

array([11, None, 6.0, 43.0, 354.0, 8.0, 40.5, 108.32043925921123,
       72.17846806844075, 196, 202,
       '[ 2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2\n 10 10 10 10 10 10 10 10 10 10 10 10]'],
      dtype=object)

In [8]:
om = np.array([
[0,4,5,6,4,5,5,5,3,6,3],
[6,0,5,5,4,4,5,3,6,4,6],
[5,5,0,6,3,3,5,6,3,5,3],
[4,5,4,0,4,4,4,6,4,4,4],
[6,6,7,6,0,5,6,7,5,7,3],
[5,6,7,6,5,0,4,7,7,7,4],
[5,5,5,6,4,6,0,5,5,5,4],
[5,7,4,4,3,3,5,0,5,2,5],
[7,4,7,6,5,3,5,5,0,6,5],
[4,6,5,6,3,3,5,8,4,0,3],
[7,4,7,6,7,6,6,5,5,7,0]])
measure(11,0,rep=3,om=om)

Execution without init...
374.8329613208771
[[10  4  6  5  8  0  2  9  3  7  1]
 [10  4  6  5  8  0  9  2  3  7  1]
 [10  4  6  5  8  2  0  9  3  7  1]]
Obtained distance is [227]
[ 5 10  6  8  1  3  2  9  4  7  0]
Execution with borda... (distance = [235])
[ 7  5  8  9  1  2  4 10  3  6  0]
354.17962797482807
[[10  4  6  5  8  0  2  9  3  7  1]
 [10  4  6  5  8  0  9  2  3  7  1]
 [10  4  6  5  8  2  0  9  3  7  1]]


array([11, None, 5.0, 38.0, 329.0, 3.833333333333333, 20.0,
       374.8329613208771, 354.17962797482807, 227, 235, '[10 10 10]'],
      dtype=object)

In [10]:
om = np.array([
[0,4,3,4,4,7,3,4,5,5,6],
[6,0,4,6,3,7,3,3,5,6,6],
[7,6,0,7,7,9,6,3,6,7,8],
[6,4,3,0,6,8,4,5,6,5,6],
[6,7,3,4,0,7,4,3,6,5,6],
[3,3,1,2,3,0,4,2,4,5,5],
[7,7,4,6,6,6,0,7,9,5,8],
[6,7,7,5,7,8,3,0,4,6,5],
[5,5,4,4,4,6,1,6,0,5,6],
[5,4,3,5,5,5,5,4,5,0,5],
[4,4,2,4,4,5,2,5,4,5,0]])
measure(11,0,rep=1,om=om)

Execution without init...
189.7630970478058
[[ 6  7  2  3  4  1  0  8  5  9 10]
 [ 6  7  2  3  4  1  0  8  5 10  9]
 [ 6  7  2  3  4  1  0  8  9  5 10]
 [ 6  7  2  3  4  1  0  8  9 10  5]
 [ 6  7  2  3  4  1  0  8 10  5  9]
 [ 6  7  2  3  4  1  0  8 10  9  5]
 [ 6  7  2  3  4  1  0  9  8  5 10]
 [ 6  7  2  3  4  1  0  9  8 10  5]
 [ 6  7  2  3  4  1  8  0  5  9 10]
 [ 6  7  2  3  4  1  8  0  5 10  9]
 [ 6  7  2  3  4  1  8  0  9  5 10]
 [ 6  7  2  3  4  1  8  0  9 10  5]
 [ 6  7  2  3  4  1  8  0 10  5  9]
 [ 6  7  2  3  4  1  8  0 10  9  5]
 [ 6  7  2  3  4  1  8  9  0  5 10]
 [ 6  7  2  3  4  1  8  9  0 10  5]
 [ 6  7  2  3  4  1  9  0  8  5 10]
 [ 6  7  2  3  4  1  9  0  8 10  5]
 [ 6  7  2  3  4  1  9  8  0  5 10]
 [ 6  7  2  3  4  1  9  8  0 10  5]
 [ 6  7  2  3  4  8  1  0  5  9 10]
 [ 6  7  2  3  4  8  1  0  5 10  9]
 [ 6  7  2  3  4  8  1  0  9  5 10]
 [ 6  7  2  3  4  8  1  0  9 10  5]
 [ 6  7  2  3  4  8  1  0 10  5  9]
 [ 6  7  2  3  4  8  1  0 10  9  5]
 [ 6  7  2  3  4  8 

array([11, None, 5.0, 43.0, 346.0, 5.666666666666666, 35.333333333333336,
       189.7630970478058, 152.4457447528839, 210, 212,
       '[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6\n 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]'],
      dtype=object)